fixed #71
telepresence-platform/cocosoco pull request #121
Opened 2021-03-02 15:24 UTC by nboufSD

2021-03-02 15:30 UTC, nboufSD commented
https://github.com/telepresence-platform/cocosoco/pull/121/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R10-R12

で、何らかの条件で**'Window' is defined but never used**のエラーが出るので、この部分だけeslintの回避を行いたいのですが、できるのでしょうか…？
（また、このリンク先の部分を削除すると、別のエラーが出ます）

2021-03-02 23:05 UTC, dadaa requested changes
ありがとうございますー
レビューいたしましたので、確認ください。

2021-03-02 23:05 UTC, dadaa commented on src/components/AudienceItem.css
> +}
speaking のときに selected なサインが消えてしまいますね。
どう思います？ @yogurt0713

2021-03-02 23:05 UTC, dadaa commented on src/components/AudienceItemVideo.tsx
> +class AudienceItemVideo extends React.PureComponent<IProps> {
このコンポーネントは AudienceItem に依存しなくても良いと思います。
加えて Video だと見えることを想像しちゃいそうなので `AudienceStream` でどうでしょうか。

2021-03-02 23:05 UTC, dadaa commented on src/types.ts
> +
今のところ一つの属性しか管理しないので Member の isSpeaking で十分だと思います。
これは削除してしまいましょう。
reducer/component で AudioState を見ているところは全て、Member の isSpeaking に差し替えてしまいましょう。

2021-03-02 23:06 UTC, dadaa commented
> https://github.com/telepresence-platform/cocosoco/pull/121/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R10-R12
> 
> で、何らかの条件で**'Window' is defined but never used**のエラーが出るので、この部分だけeslintの回避を行いたいのですが、できるのでしょうか…？
> （また、このリンク先の部分を削除すると、別のエラーが出ます）

https://github.com/microsoft/TypeScript/issues/31686
このやり方で治ります？

2021-03-03 13:38 UTC, nboufSD commented on src/actions.ts
ありがとうございます！
修正しました。

2021-03-03 13:39 UTC, nboufSD commented on src/actions.ts
> +}>("UPDATE_ISSPEAKING");
すみません！削除しました。

2021-03-03 13:44 UTC, nboufSD commented on src/actions.ts
> +}>("UPDATE_AUDIOSTATE");
ここなのですが、audienceにisSpeakingをくっつけると、isSpeakingの更新があるたびにaudienceItemVideoがロードされてしまい、_updateVideoでエラー（前のミーティングで相談させていただいたエラー）が出てしまうので、audienceとは別に管理するようにしています。

この考え方は問題無いでしょうか？

2021-03-03 13:45 UTC, nboufSD commented on src/actions.ts
> +function setisSpeaking(
ありがとうございます！修正しました。

2021-03-03 13:50 UTC, dadaa commented on src/actions.ts
> +}>("UPDATE_AUDIOSTATE");
`AudienceStream` で audience を prop で持つとおっしゃる通りの動きになると思います。
なので、props には stream を持つようにすれば、おそらく stream が更新されない限り、_updateVideo は呼ばれなくなるのでエラーを回避できるはずです。

2021-03-03 13:57 UTC, nboufSD commented on src/actions.ts
> +  analyserNode.fftSize = 128;
8と16は対応してないので（参照：https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/fftSize）、32で修正しました！
（閾値も変更してあります）

2021-03-03 13:58 UTC, nboufSD commented on src/actions.ts
> +}>("UPDATE_AUDIOSTATE");
なるほど！！ありがとうございます！
修正します！

2021-03-03 14:24 UTC, nboufSD commented on src/actions.ts
> +  let sum = 0;
すいません！修正しました！

2021-03-03 14:35 UTC, nboufSD commented on src/actions.ts
> +      } else if (isNaN(value - analyserNode.fftSize)) {
valueにundefinedが出力された場合に、計算結果がNanになってしまうので、それを回避しています。

2021-03-03 14:37 UTC, nboufSD commented on src/actions.ts
> +    }
ありがとうございます！修正しました。

2021-03-03 14:39 UTC, nboufSD commented on src/actions.ts
> +    sum = 0;
削除しました！ありがとうございます。

2021-03-03 14:49 UTC, nboufSD commented on src/actions.ts
> +        peerId: audience.peerId,
peerIdは取れているので、audience.peerIdにする必要は確かに無いですね…

ここでaudienceを検索して、if (audience && peerId) としているのは、UpdateAudienceを使用する時にaudienceが存在しない時があるかもしれないと思い、判別する様にしています。
（peerIdはundefind回避でifに入れてます）

2021-03-03 14:50 UTC, nboufSD commented on src/actions.ts
> +  const getAudioState = function () {
ありがとうございます！修正しました！

2021-03-03 14:55 UTC, nboufSD commented on src/actions.ts
> +  const Interval_getAudioState = setInterval(getAudioState, 1000 / 50);
ここでsetする様にしました！
audioStatusInterval をletじゃなくてconst で定義しているのですが、大丈夫でしょうか？

2021-03-03 14:55 UTC, nboufSD commented on src/actions.ts
> +  );
削除しました！

2021-03-03 14:58 UTC, nboufSD commented on src/actions.ts
> +    case "isSpeaking-updated": {
すいません！修正します！
他のAudioStateのような変数名もAudioStatusに変更すべきでしょうか？

2021-03-03 14:59 UTC, nboufSD commented on src/components/AudienceItem.css
> +}
selectedの時は、内側の枠が変化する様にしてあるのですが、どうでしょうか？

2021-03-03 15:01 UTC, nboufSD commented on src/components/AudienceItemVideo.tsx
> +class AudienceItemVideo extends React.PureComponent<IProps> {
AudienceItem に依存しないとは、AudienceItem内に入れない様にするという認識で宜しいでしょうか？

2021-03-03 15:02 UTC, nboufSD commented on src/components/AudienceItemVideo.tsx
> +class AudienceItemVideo extends React.PureComponent<IProps> {
名前はすぐに修正します！

2021-03-03 15:04 UTC, nboufSD commented on src/types.ts
> +
ありがとうございます！
修正しました！

2021-03-03 15:13 UTC, nboufSD commented
> > https://github.com/telepresence-platform/cocosoco/pull/121/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R10-R12
> > で、何らかの条件で**'Window' is defined but never used**のエラーが出るので、この部分だけeslintの回避を行いたいのですが、できるのでしょうか…？
> > （また、このリンク先の部分を削除すると、別のエラーが出ます）
> 
> [microsoft/TypeScript#31686](https://github.com/microsoft/TypeScript/issues/31686)
> このやり方で治ります？

僕もそのページを見て対処したのですが、直っていない状況です…
（declare globalをindexではなく、actionに記述しても同様でした…）

2021-03-03 22:58 UTC, dadaa requested changes

2021-03-03 22:58 UTC, dadaa commented on src/actions.ts
あ、違います。オーディオのチェックをする interval は、一つのオーディエンスに対して絶対に１つしか動かないので、map で管理する必要がありません。
`let audioStatusInterval = timerid;`
こんな感じで間に合うはずです。

2021-03-03 22:58 UTC, dadaa commented on src/actions.ts
> +      } else if (isNaN(value - analyserNode.fftSize)) {
なぜ value が undefined になってしまうのでしょうか？
まずはその理由を知りたいです。
それを知った上で、sum に 1 プラスすべきなのかを判断したいと思います。

2021-03-03 22:58 UTC, dadaa commented on src/actions.ts
> +    if (audience && peerId) {
この audience は自分自身のものなので、確実にある状態になってから、startUpdatingAudioState を呼んではいかがでしょうか？

2021-03-03 22:58 UTC, dadaa commented on src/actions.ts
> +      });
毎回全てのオーディエンスにディスパッチするのはオーディエンスの数が多くなればなるほど指数関数的に通信が増えてしまいます。少し、抑える工夫が必要そうです。
まずは新しく計算した isSpeaking が、state の中にある isSpeaking と比較して違う場合、これを送ることで抑制できそうです。

それと、たとえば、１秒以上にかけて threshold を超えていたら isSpeaking と判定したり、isSpeaking が true の場合は、逆に１秒以上静かになったら false にするなども必要かもしれません。
@yogurt0713 これについては、ご意見いただければ。

2021-03-03 22:58 UTC, dadaa commented on src/actions.ts
> +  const timerId = setInterval(updateAudioState, 1000 / 50);
もしかすると、interval ではなく、setTimeout にした方が良いかもです。
updateAudioState の終わりに setTimeout で自分を呼び出す感じで。

2021-03-03 22:58 UTC, dadaa commented on src/components/AudienceItem.css
> +}
おお？ほんとですか？
ソースコードを見る感じだと、--selected と --speaking の違いはその background-color の変化しか見えないような？

2021-03-03 23:00 UTC, dadaa commented on src/components/AudienceItemVideo.tsx
> +class AudienceItemVideo extends React.PureComponent<IProps> {
違います。単純に名前の問題です。
AudienceItem から始まると AudienceItem に依存していそうな気がしますが、このコンポーネントは実際にはどこで管理しても良いはずです。したがって、Item を抜きたいというのがそもそもの意図でした。よって `AudienceStream` を提案しました。

2021-03-03 23:03 UTC, dadaa commented
#

> > > https://github.com/telepresence-platform/cocosoco/pull/121/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R10-R12
> > > で、何らかの条件で**'Window' is defined but never used**のエラーが出るので、この部分だけeslintの回避を行いたいのですが、できるのでしょうか…？
> > > （また、このリンク先の部分を削除すると、別のエラーが出ます）
> > 
> > 
> > [microsoft/TypeScript#31686](https://github.com/microsoft/TypeScript/issues/31686)
> > このやり方で治ります？
> 
> 僕もそのページを見て対処したのですが、直っていない状況です…
> （declare globalをindexではなく、actionに記述しても同様でした…）

そうですか？
https://github.com/microsoft/TypeScript/issues/31686#issuecomment-636257758
ここにあるように、declarations.d.ts などの追加とかがなされていないようで、これも試しましたか？

2021-03-05 14:54 UTC, dadaa requested changes

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +      if (state.localPeer?.id) {
`if (state.localPeer) {`

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +  let state = store.getState()?.state;
ここで取得した state は使っていないので、この行は必要ありません。

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +  const averages = new Array(10);
この 10 は、後に出てくる 1000/10 の 10 と関連があるので、定数にしてください。

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +    let sum = 0;
使用する直前に定義するのが基本なので、for の上に移動してください。

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +      // Reason for setting "128" https://www.w3.org/TR/webaudio/#dom-analysernode-getbytetimedomaindata
```
See the following document to know the reason why this depends on 128.
https://www.w3.org/TR/webaudio/#dom-analysernode-getbytetimedomaindata
```

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +      }
ちょっと確認してもらいたいんですけど、
`sum += Math.abs(value - 128);`
で、この４行を置き換えるんじゃない？

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +    if (averages.findIndex(element => element === undefined) === -1) {
ちょっとこの式の意味がわからないんだけど、どういう意味です？
あと、averages の配列、new Array(10) したあとに、
`averages.fill(0)`
で、全てを 0 にしておいた方が良いと思いました。

2021-03-05 14:54 UTC, dadaa commented on src/actions.ts
> +      const averages_sum = averages.reduce(function (acc, cur) {
基本 CamelCase にしたいので `averages_sum` も CamelCase にしてください。
あと acc, cur の意味がわからないので、わかりやすい単語にしてください。

2021-03-05 14:54 UTC, dadaa commented on src/components/AudienceItem.tsx
> +                : " audience-item--inner") +
AudienceItem の中の inner なので、
`audience-item__inner` 
および
`audience-item__inner--mine` 
で。

2021-03-05 14:54 UTC, dadaa commented on src/components/AudienceItem.tsx
> +              (audience.isSpeaking ? " audience-item--speaking" : "")
`audience-item__inner--speaking`

2021-03-05 14:54 UTC, dadaa commented on src/components/AudienceStream.tsx
> +        className="audience-item--video"
`audience-stream`

2021-03-05 15:05 UTC, dadaa commented on src/actions.ts
> +    if (averages.findIndex(element => element === undefined) === -1) {
あー、わかった気がする。全ての配列に値が入るのを待っているのか。
それより、averages.fill(0) で、全てを 0 で埋めてしまえば、この評価は要らなくなりそうです。

2021-03-05 15:08 UTC, nboufSD commented on src/actions.ts
> +    if (averages.findIndex(element => element === undefined) === -1) {
レビューありがとうございます。
全部入っているかの判定をしようと思ってそう書いていましたが、fillで埋めるように変更修正します！

2021-03-06 02:57 UTC, nboufSD commented on src/actions.ts
> +      if (state.localPeer?.id) {
修正しました！

2021-03-06 02:58 UTC, nboufSD commented on src/actions.ts
> +          state.localPeer?.id,
すいません！修正しました！

2021-03-06 02:59 UTC, nboufSD commented on src/actions.ts
> +  let state = store.getState()?.state;
削除しました！すいません！

2021-03-06 03:00 UTC, nboufSD commented on src/actions.ts
> +  const averages = new Array(10);
修正しました！

2021-03-06 03:00 UTC, nboufSD commented on src/actions.ts
> +    let sum = 0;
すいません！修正しました。

2021-03-06 03:01 UTC, nboufSD commented on src/actions.ts
> +      // Reason for setting "128" https://www.w3.org/TR/webaudio/#dom-analysernode-getbytetimedomaindata
ありがとうございます！修正しました。

2021-03-06 03:03 UTC, nboufSD commented on src/actions.ts
> +      }
置き換えれました！
ありがとうございます！

2021-03-06 03:29 UTC, nboufSD commented on src/actions.ts
> +      const averages_sum = averages.reduce(function (acc, cur) {
averages_sum　：　averagesSum
acc　：　accumulator
cur　：　currentValue

に変更しました！

2021-03-06 03:33 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +                : " audience-item--inner") +
ありがとうございます！修正しました！

2021-03-06 03:33 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +              (audience.isSpeaking ? " audience-item--speaking" : "")
修正しました。

2021-03-06 03:34 UTC, nboufSD commented on src/components/AudienceStream.tsx
> +        className="audience-item--video"
修正しました。

2021-03-06 03:59 UTC, dadaa approved these changes

2021-03-06 03:59 UTC, dadaa commented on src/actions.ts
> +      1000 / averageSize
0.1 秒ごとにこの処理をするのは、少しやりすぎな気もしますね。もっとアバウトでも良いのかも。
たとえば0.25秒ごととか。なるべく分析の数を減らしたいので、ちょっと探ってみてください。

@yogurt0713 
現在最新の1秒を調べてるけど、それを2秒ぐらいに伸ばしても良いかも？
そしたら 0.5 秒ごとぐらいの分析に減らせるかな。
このあたりは、実際に使ってみてかな。どう思います？

2021-03-06 04:04 UTC, yogurt0713 commented on src/actions.ts
> +      1000 / averageSize
さきほど2台でちょっとテストしてみました．分析負荷がどれくらいかかるのかちょっと気になっていたのでなるべく負荷が下げられるちょうどよい閾値で設定したいですね．conventiona settingsではいい感じで反応してくれています．アバウトバージョンを何パターンか試してみるというのが良さそうですね．

2021-03-06 05:06 UTC, nboufSD commented on src/actions.ts
> +      1000 / averageSize
最新の2秒を調べるようにすると、応答性が悪くなるような感じがあります（反応が遅れる）
また、0.1 秒ごとの処理を0.25秒ごとに変更しても特に変化は感じられなかったので、0.25秒ごとに処理を行うようにしても良さそうです。
（1秒ごとの処理にしてもあまり変化が感じられなかったので、1秒ごとでも良いかもしれません。そうすると、averages配列を用いた処理は必要なくなってしまうのですが…）

2021-03-06 05:40 UTC, dadaa commented on src/actions.ts
> +  const threshold = 5;
これ、前後に使っている場所が無いけれど、waitTime と同様こちらで適当に決める定数なので、waitTime の上に書いておきましょうか。それと threshold はあまりに一般的なので、`speakingThreshold` とかはどうでしょうか。

2021-03-06 05:41 UTC, dadaa commented on src/actions.ts
> +  const waitTime = 500;
updateIntervalTime ?

2021-03-06 05:43 UTC, dadaa commented on src/actions.ts
> +  const rangeTime = 5000;
inspectionRangeTime?

2021-03-06 07:22 UTC, nboufSD commented on src/actions.ts
> +  const threshold = 5;
場所と名称変更を行いました！ありがとうございます！

2021-03-06 07:23 UTC, nboufSD commented on src/actions.ts
> +  const waitTime = 500;
変更しました！

2021-03-06 07:24 UTC, nboufSD commented on src/actions.ts
> +  const rangeTime = 5000;
変更しました！

2021-03-07 04:00 UTC, merged