add_map_currentlocation
telepresence-platform/cocosoco pull request #15
Opened 2020-11-09 14:05 UTC by nboufSD

2020-11-10 09:09 UTC, dadaa reviewed
位置情報を常に最新に更新するためには `watchPosition()` が適しているように見えます。
https://developer.mozilla.org/ja/docs/Web/API/Geolocation/watchPosition
これを使ってみてもらえます？

作りとしてはおそらく以下のようになるかな？と思います。
* 元々あったコードを復活させる。
* watchPosition() をコールバック関数付きで呼ぶ (今の getCurrentPosition() を呼ぶ方法と同じ感じで良いと思います)
* コールバック関数が呼ばれたら (位置情報が更新されたら)、`OnPeerSelectedAction` と同じような `OnMapLocationChangedAction` みたいなアクション作って、それ経由で reducer 内の state を更新する。

どうでしょうか？？

2020-11-10 09:51 UTC, nboufSD commented
ありがとうございます！
そのようになるように修正します！

2020-11-11 07:05 UTC, dadaa requested changes
ありがとうございます！
レビューコメントを確認ください〜

2020-11-11 07:05 UTC, dadaa commented on src/components/MapPanel.tsx
> +    });
コンポーネントは基本的に UI に関わるところを担うので、こういうロジックは action が適していると思います。
InitializeMapAction 内でこれを起動してはどうでしょうか？

2020-11-11 08:34 UTC, nboufSD commented on src/components/MapPanel.tsx
> +    });
そっちの方が良いですね！
修正します！

2020-11-11 09:11 UTC, nboufSD commented on src/components/MapPanel.tsx
> +    });
質問なのですが, action内でこの部分の記述を行うと,watchPositionがうまく作動しない（actionが呼ばれた時のみしか作動せず,位置情報の変化を読み取れない）のですが, これはどうしたら良いでしょうか？
InitializeMapActionを一定時間間隔で呼び出す方法とかを今考えているのですがどうでしょうか？

2020-11-11 09:13 UTC, dadaa commented on src/components/MapPanel.tsx
> +    });
おや？ほんと？
ソースがみたいですー

2020-11-14 09:39 UTC, nboufSD commented
・participationで,現在位置の取得のためにgetCurrentPositionの追加（初期値のまま現在位置が反映されないのを防ぐため）
・現在位置にpin_legの表示

以上の２点の追加,修正を行ったのでご確認をお願いします.

2020-11-14 09:54 UTC, dadaa requested changes
いい感じです！
少し変えたいところがあったので、確認ください！

2020-11-14 09:54 UTC, dadaa commented on src/components/MapPanel.tsx
> +import pin_leg_image from "./pin_leg.png";
他の変数は全て CamelCase で統一してあるので、ここも
`pinImage`
などで統一したいところです。
ちなみに、`pin_leg_image` のようなアンダースコアでつなげる名前の付け方を snake case と呼びます。

2020-11-14 09:54 UTC, dadaa commented on src/components/MapPanel.tsx
> +    InitializeMap(map.key, map.lat, map.lng, map.defaultZoom);
ここでまた Action を呼ぶのはなんだか不思議な感じがします。
要らないんじゃない？

2020-11-14 09:54 UTC, dadaa commented on src/components/Participation.tsx
> +    navigator.geolocation.getCurrentPosition(pos => {
当初、これらのデータは URL のパラメータから取ろうとしてたので、ここから渡すために InitializeMap のパラメータに lat, lng を入れてましたけど、もうそうではないですね。
そうなると、地図関係の初期化は全て InitializeMap を見ればわかるようにするという意味では、getCurrentPosition も InitializeMap で書く方が妥当かも知れません。

defaultZoom はどうしよう。
defaultZoom は利用者によって変えたいことがあるかな？ @yogurt0713 ??

2020-11-14 09:56 UTC, nboufSD commented on src/components/MapPanel.tsx
> +import pin_leg_image from "./pin_leg.png";
勉強になります！！
PinImageに修正します！
ありがとうございます！

2020-11-14 09:59 UTC, nboufSD commented on src/components/MapPanel.tsx
> +    InitializeMap(map.key, map.lat, map.lng, map.defaultZoom);
確かに…削除します！

2020-11-14 10:04 UTC, nboufSD commented on src/components/Participation.tsx
> +    navigator.geolocation.getCurrentPosition(pos => {
getCurrentPositionをInitializeMapで書くとInitializeMapが呼び出される度にgetCurrentPositionが回ってしまうので,watchPositionと相性が悪い？のかなと思ってしまったのですが,どうでしょうか…？

2020-11-14 10:09 UTC, yogurt0713 commented on src/components/Participation.tsx
> +    navigator.geolocation.getCurrentPosition(pos => {
どうしましょう．defaultZoomがデバイス依存かも（PCとスマホ，タブレットだと画面サイズがそもそも違うので地図の必要な解像度が異なるようにおもいますが，自分で変えることもできるし．．．悩みどころです）

2020-11-14 10:42 UTC, dadaa commented on src/components/Participation.tsx
> +    navigator.geolocation.getCurrentPosition(pos => {
InitializeMap は一度しか呼ばれないはずなので、問題ないんじゃないかしら？

2020-11-14 10:58 UTC, dadaa commented on src/components/Participation.tsx
> +    navigator.geolocation.getCurrentPosition(pos => {
@yogurt0713 じゃ、とりあえず固定で良いですかね。
@nboufSD そしたら、defaultZoom も InitializeMap で定義するようにしたら良いと思います。
つまり、InitializeMap のパラメータは key だけ。

2020-11-14 11:14 UTC, nboufSD commented on src/components/Participation.tsx
> +    navigator.geolocation.getCurrentPosition(pos => {
確かに！（上の修正箇所でInitializeMapをMapPanelで呼んでいたので勘違いしていました）
InitializeMap のパラメータが key だけになるように変更します！

2020-11-14 12:28 UTC, dadaa requested changes
ほぼ完璧！
ひとつだけ文字を変えたいです！

2020-11-14 12:28 UTC, dadaa commented on src/components/MapPanel.tsx
> +  return <img src={pinImage} alt="pinImage" />;
alt はこのピンの説明になるから、
`current position`
とかにしておきます？

2020-11-14 12:30 UTC, nboufSD commented on src/components/MapPanel.tsx
> +  return <img src={pinImage} alt="pinImage" />;
そうします！

2020-11-14 12:35 UTC, dadaa approved these changes
ありがとうございましたー！

2020-11-14 12:35 UTC, merged