StreamingOnlyPresenter
telepresence-platform/cocosoco pull request #28
Opened 2020-11-26 08:49 UTC by nboufSD

2020-11-28 03:00 UTC, dadaa requested changes
ありがとうございます〜
ほぼ OK です！
ちょっとだけ変更したいところがあったので、確認ください。

2020-11-28 04:18 UTC, dadaa commented
https://github.com/telepresence-platform/cocosoco/issues/22
この issue が解決できるので、コミットメッセージを 
fixed #22 
としてください

2020-11-28 06:58 UTC, nboufSD commented on src/actions.ts
> +
修正しました！

2020-11-28 07:00 UTC, nboufSD commented on src/actions.ts
> +      }
承知しました！

2020-11-28 07:00 UTC, nboufSD commented on src/components/Pointing.tsx
>    private _videoRef = React.createRef<HTMLVideoElement | any>();
消します！

2020-11-28 07:01 UTC, nboufSD commented on src/reducer.ts
> +    const localStream = state?.localStream;
修正します！

2020-11-28 07:15 UTC, dadaa commented on src/actions.ts
> +      }
この処理がなされていないような気がします！
ParticipateAction の reducer で処理しましょう。

2020-11-28 07:16 UTC, dadaa commented
> #22
> この issue が解決できるので、コミットメッセージを
> fixed #22
> としてください

これもお願いしマス！

2020-11-28 07:16 UTC, dadaa requested changes
いくつかコメントしましたー

2020-11-28 07:18 UTC, nboufSD commented on src/actions.ts
> +      }
すいません！
勘違いしてOnPeerSelectedActionに書いていました！

2020-11-28 07:22 UTC, nboufSD commented
プルリクのメッセージのタイトルを”fixed #22”に変更してコミットメッセージを変更した気になってました！
申し訳ないです！

2020-11-28 07:27 UTC, dadaa requested changes
あとちょっと整形するだけ！

2020-11-28 07:27 UTC, dadaa commented on src/reducer.ts
> +    }
audience 系の処理の間に、別の処理が入るとみづらくなっちゃうから、71行目にこれを追加して、さらに下に空行を入れてください。

2020-11-28 07:27 UTC, dadaa commented on src/reducer.ts
> +    }
ここも下に 1 行入れてください。

2020-11-28 07:49 UTC, nboufSD commented on src/reducer.ts
> +    }
修正しました！

2020-11-28 07:50 UTC, nboufSD commented on src/reducer.ts
> +    }
修正しました！

2020-11-29 00:00 UTC, dadaa requested changes
これで最後の変更だと思います！

2020-11-29 00:00 UTC, dadaa commented on src/reducer.ts
> +    for (const track of localStream?.getVideoTracks() || []) {
nit: ここは "?" が削除できそうなので、消してください-

2020-11-29 03:39 UTC, dadaa approved these changes
Thank you very much!

2020-11-29 03:39 UTC, merged

2020-11-29 04:06 UTC, nboufSD commented
ありがとうございました！