fixed #23
telepresence-platform/cocosoco pull request #37
Opened 2020-11-30 14:11 UTC by nboufSD

まだ全然できてないです…すいません！

今はparticipate(最初の画面)で静止画を取得してdataURLにしてactionに送り,actionでlocalpeer.idとセットにしてreducerに送り,reducerで上記の二つの値をIcon型（typesで設定しました）としてstoreに送ります.
そしてそのstoreのIcon型の値をAudienceItemで参照することでアイコンを静止画にします.

今の問題としては,
1. actionのparticipateからroomにsendできないこと
2.送れたとしても,localpeer.idで区別したdataURLをそれぞれ保持できないのではないかということ
　（storeを更新する感じだと最後に入室した一人分のデータしか保持できない？）

この二つの点について相談させて頂きたいです！
よろしくお願いします.

2020-12-03 12:54 UTC, dadaa requested changes
ありがとさまー！
レビューしましたので確認くださいー

2020-12-03 12:54 UTC, dadaa commented on src/actions.ts
> +export const OnParticipationIconAction = actionCreator<{
OnIconUpdatedAction なんて名前でいかがでしょうか？

2020-12-03 12:54 UTC, dadaa commented on src/actions.ts
> +}>("ICON_ADDED");
ON_ICON_UPDATED ?

2020-12-03 12:54 UTC, dadaa commented on src/actions.ts
> +        onStream(dispatch, getState(), stream, dataURL);
ここで dataURL を渡すのはやめておきましょう。

2020-12-03 12:54 UTC, dadaa commented on src/actions.ts
> +  dataURL: string
ここで dataURL のパラメータは受け取らず、store.state で自分の audience の dataURL を参照するようにしましょう。

2020-12-03 12:54 UTC, dadaa commented on src/actions.ts
> +    type: "icon-added",
nit: icon-updated ?
(今後、アイコンの更新もあるのではないかと想像します)

2020-12-03 12:54 UTC, dadaa commented on src/components/AudienceItem.css
> +}
`.audience-item__video` はもう使わないので削除してください。

2020-12-03 12:54 UTC, dadaa commented on src/components/AudienceItem.tsx
> +  icon?: string;
いらない？

2020-12-03 12:54 UTC, dadaa commented on src/components/AudienceItem.tsx
> +    const { isSelected, icon } = this.props;
props に audience があるので、audience.dataURL で icon を指定できると思います。

2020-12-03 12:54 UTC, dadaa commented on src/components/AudienceList.tsx
> +  dataURL?: string;
いらない？

2020-12-03 12:54 UTC, dadaa commented on src/components/AudienceList.tsx
> +            icon={audience.dataURL}
AudienceItem にも書きましたけど、audience を渡しているので、その中から dataURL を参照すれば良いと思います。

2020-12-03 12:54 UTC, dadaa commented on src/components/AudienceList.tsx
> +    dataURL: store.state.dataURL,
要らない？

2020-12-03 12:54 UTC, dadaa commented on src/components/Participation.css
> +  /*transform: translate(-6%, -23%);*/
コメントは削除しましょ。

2020-12-03 12:54 UTC, dadaa commented on src/components/Participation.tsx
> +  dataURL?: string;
いらない？

2020-12-03 12:54 UTC, dadaa commented on src/components/Participation.tsx
> +    this.setState({ dataURL });
state に dataURL を持つ理由が今のところなさそうな気がします。

2020-12-03 12:54 UTC, dadaa commented on src/components/Participation.tsx
> +    participate(key, network, room, dataURL);
participate アクションの中でも stream を取る処理がかかれているので、ここから stream を同アクションに渡してしまいましょう。

2020-12-03 12:54 UTC, dadaa commented on src/reducer.ts
> +  peerId?: string;
要らない？

2020-12-03 12:54 UTC, dadaa commented on src/reducer.ts
> +    // オーディエンスを更新
このコメントはいらないかな？

2020-12-03 12:57 UTC, nboufSD commented on src/actions.ts
> +export const OnParticipationIconAction = actionCreator<{
その名前でいかせて頂きます！

2020-12-03 13:05 UTC, nboufSD commented on src/actions.ts
> +}>("ICON_ADDED");
それにします！

2020-12-03 13:06 UTC, nboufSD commented on src/actions.ts
> +        onStream(dispatch, getState(), stream, dataURL);
削除します！

2020-12-03 13:12 UTC, nboufSD commented on src/actions.ts
> +  dataURL: string
変更しました！

2020-12-03 13:12 UTC, nboufSD commented on src/actions.ts
> +    type: "icon-added",
確かに…！
変更します！

2020-12-03 13:16 UTC, nboufSD commented on src/components/AudienceItem.css
> +}
削除しました！

2020-12-03 13:18 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +  icon?: string;
iconはAudienceListから渡しているので必要だと思っていますが,lcalPeerは要らないです！
削除しました！

2020-12-03 13:21 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +  icon?: string;
すいません！
下のレビューを見させていただいたらiconも要らないとわかりました！
削除します！

2020-12-03 13:22 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +    const { isSelected, icon } = this.props;
icon → audience　に変更しました！

2020-12-03 13:22 UTC, nboufSD commented on src/components/AudienceList.tsx
> +  dataURL?: string;
削除しました！

2020-12-03 13:22 UTC, dadaa commented on src/components/AudienceItem.tsx
> +  icon?: string;
AudienceItem には audience が渡されているので、audience.dataURL を AudienceItem の内部で見れば良いと思います。従って、icon が要らないのではないかなと、想像しています。

2020-12-03 13:22 UTC, nboufSD commented on src/components/AudienceList.tsx
> +            icon={audience.dataURL}
icon は削除してaudienceからの参照に変更しました！

2020-12-03 13:23 UTC, nboufSD commented on src/components/AudienceList.tsx
> +    dataURL: store.state.dataURL,
削除しました！

2020-12-03 13:23 UTC, nboufSD commented on src/components/Participation.css
> +  /*transform: translate(-6%, -23%);*/
すいません！！
削除します！

2020-12-03 13:29 UTC, nboufSD commented on src/components/Participation.tsx
> +  dataURL?: string;
dataURLは削除しました！
localStreamはasync componentDidMount()の中で定義しているのでstateにセットする必要があるのかな？と思ったので削除していませんが大丈夫でしょうか？

2020-12-03 13:29 UTC, nboufSD commented on src/components/Participation.tsx
> +    this.setState({ dataURL });
participateでdataURLを送ってactionでdispatchしているので必要ないですね！
削除します！

2020-12-03 13:31 UTC, nboufSD commented on src/components/Participation.tsx
> +    participate(key, network, room, dataURL);
participateでstreamを渡すようにして,actionのlocalStreamの定義は削除します！

2020-12-03 13:36 UTC, nboufSD commented on src/reducer.ts
> +  peerId?: string;
peerIdは削除してdataURLは残していますが大丈夫でしょうか？

2020-12-03 13:37 UTC, nboufSD commented on src/reducer.ts
> +    // オーディエンスを更新
すいません！！
消します！！

2020-12-03 14:13 UTC, nboufSD commented on src/components/AudienceList.tsx
> +            icon={audience.dataURL}
すみません…
iconの存在を消して,AudienceItemでアイコン画像をaudience.dataURLで読み込むようにしたら,同期が正常に行われなくなってしまいました…

2020-12-03 14:15 UTC, nboufSD commented on src/components/AudienceList.tsx
> +            icon={audience.dataURL}
一人目は大丈夫なのですが,二人目の同期が行われなくなってしまいました…
一人目：自分＝OK,相手側=OK
二人目：自分＝OK,相手側=NG

2020-12-03 23:58 UTC, dadaa requested changes
thanks

2020-12-03 23:58 UTC, dadaa commented on src/components/AudienceList.tsx
> +            icon={audience.dataURL}
おそらく、audience が同じインスタンスだから更新されていないのだと思います。reducer のところでコメントするので、確認ください。

2020-12-03 23:58 UTC, dadaa commented on src/reducer.ts
> +      audience.stream = stream;
同じインスタンスのフィールドを変更しているだけなので、React component は変化が無いと思い、再描画してくれていないのかもしれません。
以下のようにして試してもらえますか？

```
const index = state.audiences.findIndex(a => a.peerId === peerId);
let audiences = state.audiences;
if (index !== -1) {
  const audience = audiences[index];
  audiences[index] = Object.assign({}, audience, { stream});
  // これで動かなかったら、以下も試してみて。
  // audiences = [...state.audiences, { peerId, stream }];
} else {
  audiences = [...state.audiences, { peerId, stream }];
}
```

OnIconUpdatedAction も同様の変更をしてみてください。

2020-12-04 04:49 UTC, nboufSD commented
送っていただいたコードでiconを削除しても動作を確認できました！（少しだけ変更しました）
ありがとうございます！

2020-12-04 04:58 UTC, dadaa requested changes
ありがと〜
あともうちょいっぽいです！

2020-12-04 04:58 UTC, dadaa commented on src/actions.ts
> +
ParticipateAction で `dataURL` を送っているので、ここでは `OnIconUpdatedAction` を使わなくて良いのでは？

2020-12-04 04:58 UTC, dadaa commented on src/components/Participation.tsx
> +    const video: HTMLVideoElement = document.getElementById("mov") as any;
これは `const video = this._videoRef.current;` で置き換えられると思います。

2020-12-04 04:58 UTC, dadaa commented on src/components/Participation.tsx
> +    const canvas: HTMLCanvasElement = document.getElementById("draw") as any;
これも video 同様に ref を使いましょう。

2020-12-04 04:58 UTC, dadaa commented on src/components/Participation.tsx
> +            id="mov"
id は削除しても大丈夫そうです。

2020-12-04 04:58 UTC, dadaa commented on src/components/Participation.tsx
> +          <canvas id="draw"></canvas>
id 消しましょう。

2020-12-04 04:58 UTC, dadaa commented on src/components/Participation.tsx
> +        <div className="participation_capture_image">
nit: rename with `participation__capture`

2020-12-04 04:58 UTC, dadaa commented on src/components/Participation.tsx
> +            className="participation-item__video"
nit: rename with `participation__video`

2020-12-04 04:58 UTC, dadaa commented on src/components/Participation.css
> +}
こちらで試していないんですけど、おそらく、どちらかの clip-path は要らないんじゃないかな？

2020-12-04 04:58 UTC, dadaa commented on src/reducer.ts
> +  dataURL?: string;
いらない？

2020-12-04 05:25 UTC, nboufSD commented
ありがとうございます！
修正しました！

2020-12-04 05:53 UTC, dadaa requested changes
もう細かいところの修正なので、次でマージできると思います！

2020-12-04 05:53 UTC, dadaa commented on src/actions.ts
> +      });
ここは結局のところ変更が無いので、元に戻しておきましょう。

2020-12-04 05:53 UTC, dadaa commented on src/components/Participation.tsx
> +  private _canvasRef = React.createRef<HTMLVideoElement | any>();
canvas エレメントなので、HTMLCanvasElement じゃないかしら？

2020-12-04 06:06 UTC, dadaa approved these changes
thanks!

2020-12-04 07:14 UTC, dadaa requested changes

2020-12-04 07:14 UTC, dadaa commented on src/components/AudienceItem.tsx
> -    const { isMuted, isSelected } = this.props;
ここで isMuted を消してしまったため、音声がなくなってしまったのだと思います。

2020-12-04 07:14 UTC, dadaa commented on src/components/AudienceItem.tsx
> +          muted={false}
元の戻しましょう。

2020-12-04 07:48 UTC, dadaa requested changes

2020-12-04 07:48 UTC, dadaa commented on src/reducer.ts
> +    return Object.assign({}, state, { audiences });
あ、ここ、AddPeerAction と同じようにしないと、React が正しく更新されないと思います。

2020-12-04 10:16 UTC, dadaa requested changes

2020-12-04 10:16 UTC, dadaa commented on src/reducer.ts
> +      audiences = [...state.audiences];
あ、ここ間違えてますね。
```
audiences = [...state.audiences, audience];
```

2020-12-07 05:42 UTC, dadaa requested changes
おおむね、OKかと思います！

2020-12-07 05:42 UTC, dadaa commented on src/actions.ts
> +  });
`dataURL: audience?.dataURL,` は、null が送られてしまう可能性があるので、
```
if (audience) {
  store.state.room?.send({
    type: "icon-updated",
    dataURL: audience.dataURL,
    peerId: store.state.localPeer?.id,
  });
}
```
と、したい気がします。

2020-12-07 05:42 UTC, dadaa commented on src/components/AudienceItem.css
> +  height: 0vw;
`display: none;`
はたまた
`visibility: hidden;`
は、どうですか？

2020-12-07 06:58 UTC, nboufSD commented
上記のレビューについて修正しました！
また、アイコンの解像度についても修正しました！

ありがとうございます！

2020-12-07 07:05 UTC, dadaa requested changes
ほぼOKです！

2020-12-07 07:05 UTC, dadaa commented on src/components/Participation.tsx
> +  async componentDidUpdate(): Promise<void> {
ここ、もはや async にする理由が無いので、
```
componentDidUpdate() {
```
で良さそうです。

2020-12-07 07:05 UTC, dadaa commented on src/reducer.ts
> +      audiences = [...state.audiences, { peerId, stream, dataURL: undefined }];
dataURL: undefined の指定は要らないんじゃない？

2020-12-07 07:05 UTC, dadaa commented on src/reducer.ts
> +      audiences = [...state.audiences, { peerId, stream: undefined, dataURL }];
ここも stream: undefined は要らないと思います。

2020-12-07 11:52 UTC, nboufSD commented
修正しました！
（peerのopenに関係するerror処理の部分も削除しました）

2020-12-07 13:17 UTC, dadaa requested changes

2020-12-07 13:17 UTC, dadaa commented on src/actions.ts
>    // Tell who is a presenter now, to peer joined newly.
このコメントは、`type: "peer-selected",` のためのコメントなので、`if (store.state.presenter) {` の上あたりに移動できますか？

2020-12-07 13:17 UTC, dadaa commented on src/components/AudienceItem.css
> +  /*display: none;*/
削除 please.

2020-12-07 13:17 UTC, dadaa commented on src/components/Participation.tsx
> +  }
https://github.com/telepresence-platform/cocosoco/blob/dev/src/components/Presenter.tsx#L132-L162
のように、render の上に componentDidMount および componentDidUpdate を移動させてください。

2020-12-07 13:17 UTC, dadaa commented on src/components/Participation.tsx
> +    console.log("render");
削除 please

2020-12-07 13:25 UTC, nboufSD commented
すいません！console.logがかなり残っていました！

2020-12-07 13:39 UTC, dadaa requested changes

2020-12-07 13:39 UTC, dadaa commented on src/actions.ts
>    // Tell who is a presenter now, to peer joined newly.
このコメント移動してください。`if (store.state.presenter) {` の上へ。`type: "peer-selected"` のところ。

2020-12-07 13:39 UTC, dadaa commented on src/components/Participation.tsx
> +    const localStream = this.state.localStream;
この行は削除して、
`video.srcObject = this.state.localStream;`
で良さそうです。

2020-12-07 13:39 UTC, dadaa commented on src/components/Participation.tsx
> +  async componentDidUpdate(): Promise<void> {
async 要らないです。
```
componentDidUpdate() {
...
}
```

2020-12-07 13:53 UTC, dadaa approved these changes
ハードワークおつかれさまでした！

2020-12-07 13:54 UTC, merged

2020-12-07 13:56 UTC, nboufSD commented
レビューありがとうございます！
たくさん助けていただいてありがとうございました！！