fixed #24
telepresence-platform/cocosoco pull request #48
Opened 2020-12-15 11:20 UTC by nboufSD

矢印の画像を付けたのですが、participation.tsxの画面では矢印の画像のアスペクト比がおかしくなるため、cssのtransform: scaleで調整しています…
なぜ、アスペクト比がおかしくなってしまうのでしょうか…？

2020-12-16 09:48 UTC, dadaa requested changes

2020-12-16 09:48 UTC, dadaa commented on src/components/Participation.css
> +  padding: 1.2vw 0vw;
padding の上下だけの指定でしたら `padding-block` が使えそうです。
https://developer.mozilla.org/ja/docs/Web/CSS/padding-block

2020-12-16 09:48 UTC, dadaa commented on src/components/Participation.tsx
> +        <img className="participation__pointing__image" src={logo} />
"__" は、その子供、みたいな意味あいがあるので、これだと 
participation の下の pointing の下の image という構造を想像してしまいます。
ので、ここは `participation__pointing-image` でいかがでしょうか。

2020-12-16 09:49 UTC, nboufSD commented on src/components/Participation.css
> +  padding: 1.2vw 0vw;
ありがとうございます！
padding-blockに変更します！

2020-12-16 09:49 UTC, nboufSD commented on src/components/Participation.tsx
> +        <img className="participation__pointing__image" src={logo} />
ありがとうございます！
そちらに変更します！

2020-12-16 10:32 UTC, dadaa approved these changes
thanks

2020-12-18 10:38 UTC, dadaa requested changes
ひとつだけ！

2020-12-18 10:38 UTC, dadaa commented on src/components/Participation.css
> +  padding-right: 2vw;
上下左右すべてに指定するのでしたら、元の書き方の方が良いですので、お手数ですけど戻してもらえたらと思います！

2020-12-24 11:10 UTC, nboufSD commented on src/components/Participation.css
> +  padding-right: 2vw;
遅くなって申し訳ありません！
修正しました！

2020-12-24 11:23 UTC, yogurt0713 commented
動作確認いたしました　👍

2020-12-24 11:52 UTC, dadaa approved these changes
ありがとー

2020-12-24 11:52 UTC, merged