fixed #29
telepresence-platform/cocosoco pull request #49
Opened 2020-12-18 13:27 UTC by nboufSD

修正しました！
isMapEnabled_presenterでプレゼンターのmuteを判断して、trueだったらオーディエンスのトグル処理が効くようにしてます！
(これがないと、プレゼンターがmuteにしてもオーディエンスのトグル処理でマップが表示されてしまうため)

2020-12-19 23:25 UTC, dadaa requested changes
ありがとうございますー
おおよそ良さそうです！
いくつか修正したいところがあったので、コメントしておきました。

2020-12-19 23:25 UTC, dadaa commented on src/actions.ts
> +      const localpeer = state.localPeer?.id;
もし可能なら、以下にも自分がプレゼンタかどうかを調べるところがあるので、共通関数 `amIPresenter(state)` みたいなのを作って、両方で使えると良いかもです。
https://github.com/telepresence-platform/cocosoco/blob/dev/src/actions.ts#L353-L355
もちろん、ここではこのままで、別 issue でやっても良いと思います。

2020-12-19 23:25 UTC, dadaa commented on src/actions.ts
>        const result = { isEnabled };
これが使われるのは dispatch するところなので、その直前に移動させましょう。

2020-12-19 23:25 UTC, dadaa commented on src/components/MapPanel.tsx
> +  isMapEnabled_presenter: boolean;
`isPresenterMapEnabled` でどうかしら？ほかのところも。

2020-12-19 23:25 UTC, dadaa commented on src/components/MapPanel.tsx
> +    if (!map || isMapEnabled_presenter === false) {
ここで null を返すと、再度 enable になったときに改めて GoogleMap を作る必要がありそうなので、CSS で display: none を指定した方が効率よさそうな気がします。

2020-12-19 23:25 UTC, dadaa commented on src/components/MapPanel.tsx
>      const className = isMapEnabled ? "mappanel" : "mappanel--disabled";
`isMapEnabled` は自分のミュート状態を指すので、自分の地図共有がミュートしている場合でも地図が表示されないと思います。
この直下の行のコメントとも関係しますが、代わりに `isPresenterMapEnabled` をチェックしたら良いかと思います。
`const className = isMapEnabled ? "mappanel" : "mappanel--disabled";`

2020-12-20 00:30 UTC, dadaa commented on src/components/MapPanel.tsx
>      const className = isMapEnabled ? "mappanel" : "mappanel--disabled";
間違えた。
` const className = isPresenterMapEnabled ? "mappanel" : "mappanel--disabled";`

2020-12-20 06:28 UTC, nboufSD commented on src/actions.ts
> +      const localpeer = state.localPeer?.id;
function amIPresenter(state: any) {
  const presenter = state.presenter?.peerId;
  const localpeer = state.localPeer?.id;

  if (presenter === localpeer) {
    return true;
  } else {
    return false;
  }
}

のような関数にしたのですが、どうでしょうか？

2020-12-20 06:29 UTC, nboufSD commented on src/actions.ts
>        const result = { isEnabled };
修正しました！

2020-12-20 06:41 UTC, nboufSD commented on src/components/MapPanel.tsx
> +  isMapEnabled_presenter: boolean;
ありがとうございます！
変更しました！

2020-12-20 06:42 UTC, nboufSD commented on src/components/MapPanel.tsx
> +    if (!map || isMapEnabled_presenter === false) {
恐らく、下のレビューの
const className = isPresenterMapEnabled ? "mappanel" : "mappanel--disabled";
で解決できたのかな？と思っているのですが大丈夫でしょうか…？

2020-12-20 06:42 UTC, nboufSD commented on src/components/MapPanel.tsx
>      const className = isMapEnabled ? "mappanel" : "mappanel--disabled";
修正しました！
ありがとうございます！

2020-12-20 06:43 UTC, nboufSD commented
今のところ、プレゼンターがミュートにするとオーディエンスのマップはミュートになり、プレゼンターのマップはミュートにならない様になっているのですがどうでしょうか…？

2020-12-20 06:52 UTC, dadaa requested changes
ほぼOKです！
amIPresenter の関数をちょっとだけ修正してほしいです！

2020-12-20 06:52 UTC, dadaa commented on src/actions.ts
> +function amIPresenter(state: any) {
たぶん state は TStore だと思うので、any の代わりに使ってください。
https://github.com/telepresence-platform/cocosoco/blob/dev/src/actions.ts#L312

2020-12-20 06:52 UTC, dadaa commented on src/actions.ts
> +  }
おそらく、以下のようにかけます。
```
  if (!state.presenter || !state.localPeer) {
    return false;
  }
  return state.presenter.id === state.localPeer.id;
```
はじめに null チェックを行っている理由は、両方が null の場合で比較したときも true になってしまうからです。

2020-12-20 07:22 UTC, nboufSD commented on src/actions.ts
> +function amIPresenter(state: any) {
すみません！
修正します！

2020-12-20 07:25 UTC, nboufSD commented on src/actions.ts
> +function amIPresenter(state: any) {
何故かTStoreだとエラーが出てしまって、IStateだとエラーが出なかったのですが大丈夫でしょうか…？

2020-12-20 07:26 UTC, nboufSD commented on src/actions.ts
> +  }
ありがとうございます！！
修正します！

2020-12-20 07:38 UTC, dadaa approved these changes
ありがとうございました！

2020-12-20 07:43 UTC, nboufSD commented
こちらこそ有り難うございます！

2020-12-20 22:49 UTC, dadaa requested changes

2020-12-20 22:49 UTC, dadaa commented on src/actions.ts
> +      dispatch(OnMapLocationMutedAction({ isMapEnabled: state.isMapEnabled }));
あ、いまさら気づいたんですけど、ここ、その前の
`if (room) { ... }`
のブロックの中に書いた方が良いかも。
そして `state.room?.send` を `room.send` にしていただいて。

2020-12-20 22:49 UTC, dadaa commented on src/actions.ts
> +) {
引数を isMapEnabled, room, dispatch の３つすれば共通で使えると思います。

2020-12-21 01:38 UTC, nboufSD commented on src/actions.ts
> +      dispatch(OnMapLocationMutedAction({ isMapEnabled: state.isMapEnabled }));
下のレビューしてもらった内容により、共通関数で書けたので、if(room){}の中に書いていないのですが大丈夫でしょうか？

2020-12-21 01:40 UTC, dadaa commented on src/actions.ts
> +      dispatch(OnMapLocationMutedAction({ isMapEnabled: state.isMapEnabled }));
いずれにしても room があることが前提になるので、if room {} の中で書く方が理に叶っていると思います。
(そしてなるべく ? を使わないようにしたい)

2020-12-21 01:40 UTC, nboufSD commented on src/actions.ts
> +) {
すみません！
今、isMapEnabled,getstate,dispatchの三つでやってみて、動作を確認できたのですが、roomを引数に加えた方がやはり宜しいのでしょうか…？

2020-12-21 01:41 UTC, dadaa commented on src/actions.ts
> +) {
そうですね、なんども getState() を呼ぶ必要がありませんのでー

2020-12-21 01:42 UTC, nboufSD commented on src/actions.ts
> +      dispatch(OnMapLocationMutedAction({ isMapEnabled: state.isMapEnabled }));
ありがとうございます！
なるほど…では共通関数の引数にroomを加えて書き直します！

2020-12-21 01:42 UTC, nboufSD commented on src/actions.ts
> +) {
承知しました！
修正します！

2020-12-21 01:51 UTC, dadaa commented on src/actions.ts
> +        updateLocationMuting(dispatch, room, state.isMapEnabled);
ここでも自分がプレゼンターかどうかを調べる必要があるんじゃないかしら？

2020-12-21 01:54 UTC, nboufSD commented on src/actions.ts
> +        updateLocationMuting(dispatch, room, state.isMapEnabled);
ここはselectPeerの中なので、選択されたときは自分がプレゼンターなので、調べる必要はないのかな…？と思ってプレゼンターかどうかを調べていないのですが、調べた方が良いのでしょうか…？

2020-12-21 01:55 UTC, nboufSD commented on src/actions.ts
> +        updateLocationMuting(dispatch, room, state.isMapEnabled);
いや、すみません！
勘違いしてました！修正します！

2020-12-21 02:21 UTC, dadaa approved these changes
良いと思います！

2020-12-21 02:31 UTC, yogurt0713 reviewed
approveの練習をしてみたいとおもいます．こちらいまcommentです

2020-12-21 02:45 UTC, yogurt0713 approved these changes
map show/hide function 動作確認できました．

2020-12-21 02:45 UTC, merged