fixed #50
telepresence-platform/cocosoco pull request #53
Opened 2020-12-23 12:32 UTC by nboufSD

2020-12-23 14:07 UTC, dadaa requested changes
いい感じです！
いくつか修正したいところがあったので、確認くださいまし。

2020-12-23 14:07 UTC, dadaa commented on src/components/ToolList.tsx
> +      <div>
div は要らないんじゃない？

2020-12-23 14:07 UTC, dadaa commented on src/components/ToolList.tsx
> +        )}
```
const additinalClassName = amIPresenter ? "tool-list--presenter" : "tool-list--audience";
<ul className=`tool-list ${additinalClassName}`>
{amIPresenter ? (
  ... プレゼンタに必要な ToolItem
) : (
  ... オーディエンスに必要な ToolItem
)
</ul>
```
みたいな書き方はどう？

2020-12-23 14:34 UTC, nboufSD commented on src/components/ToolList.css
> +.tool-list-presenter {
なるほど…！
ありがとうございます！

2020-12-23 14:38 UTC, nboufSD commented on src/components/ToolList.css
> +.tool-list-presenter {
audienceはtool-listと同様の内容のため削除しました！

2020-12-23 14:40 UTC, nboufSD commented on src/components/ToolList.tsx
> +
ありがとうございます！
修正しました！

2020-12-23 14:41 UTC, nboufSD commented on src/components/ToolList.tsx
> +      <div>
divがないと、
"JSX 式には 1 つの親要素が必要です。"
というエラーメッセージが出てくるので、親要素として入れてます！

2020-12-23 14:51 UTC, nboufSD commented on src/components/ToolList.tsx
> +        )}
ありがとうございます！
鍵かっこだけ追加して
`<ul className={`tool-list ${additinalClassName}`}>`
の様な形で書きました！

2020-12-23 23:48 UTC, dadaa requested changes
お返事いたしましたー

2020-12-23 23:48 UTC, dadaa commented on src/components/ToolList.tsx
> +      <div>
`Fragment` を使えると思います。
https://github.com/telepresence-platform/cocosoco/blob/dev/src/components/App.tsx#L17
ドキュメントはこちら。
https://ja.reactjs.org/docs/fragments.html

2020-12-23 23:48 UTC, dadaa commented on src/components/ToolList.tsx
> +        )}
前のレビューでも少し触れましたけど&& audience 用の class が要らないのだとしたら、こういう書き方はどうですか？
```
const className = amIPresenter
      ? "tool-list tool-list--presenter"
      : "tool-list";
 // 先に共通で使う ul を作る。
<ul className={className}>
{amIPresenter ? (
  //プレゼンター用のツール群
) : (
  //オーディエンス用のツール群
)
</ul>
```
そして、おそらくこの書き方であれば、親要素(Fragmentなど)も必要ないかと思います。

2020-12-24 02:02 UTC, nboufSD commented on src/components/ToolList.tsx
> +      <div>
ありがとうございます！！
修正しました！

2020-12-24 02:30 UTC, nboufSD commented on src/components/ToolList.tsx
> +        )}
すみません！audienceが残ったままでした！
上記の様に修正しました！
（<ul ...></ul>は上記の位置に書いたのですが、判定部分の中にはFragmentがないとエラーが出てしまうので入れてます！）

2020-12-24 02:31 UTC, dadaa commented on src/components/ToolList.tsx
> +        )}
ちなみに、どんな風に書いたか教えていただけます？

2020-12-24 03:22 UTC, dadaa approved these changes
よさそうです！

2020-12-24 03:36 UTC, yogurt0713 commented
カメラ，マップアイコンレイアウト確認いたしましたー．プレゼンター以外の画面がすっきりしましたねー．現状のレイアウトでOKかと思います．

2020-12-24 04:28 UTC, dadaa approved these changes

2020-12-24 04:29 UTC, merged