fixed  #52
telepresence-platform/cocosoco pull request #54
Opened 2020-12-25 02:14 UTC by nboufSD

reducerのisMapEnabledをtrueからfalseに変更しただけなのですが、大丈夫でしょうか…？

2020-12-25 02:19 UTC, dadaa requested changes
現在は、初めに位置情報を取るためにダイアログがでますが、プライバシーなども考慮すると、位置情報の共有が始まるときに初めて location モジュールにアクセスしたいところです。これ、対応できたりしますか？

2020-12-25 02:20 UTC, nboufSD commented
レビューありがとうございます！
ちょっと調べてやってみます！

2020-12-26 15:19 UTC, dadaa requested changes
ありがとうございますー
レビューしました。ご確認くださいー

2020-12-26 15:19 UTC, dadaa commented on src/actions.ts
> +      dispatch(InitializeMapPropsAction({ key: mapkey }));
`ParticipationActoin.done` で `key` も渡して良いと思います。
そして、`InitializeMapPropsAction` は削除してしまいましょう。

2020-12-26 15:19 UTC, dadaa commented on src/actions.ts
> +      InitializeMap(dispatch, getState);
これだとマップのミュートボタン押されるたびに `InitializeMap` が呼ばれてしまいます。
たとえば、state にある `map` の `lat` および `lng` が 0 の場合は初期化するなどでどうでしょうか？
https://github.com/telepresence-platform/cocosoco/blob/dev/src/reducer.ts#L32

2020-12-26 15:19 UTC, dadaa commented on src/actions.ts
> +    dispatch(InitializeMapLocationAction.started(params));
もう `InitializeMapLocationAction` は削除してしまって良いかと思います。

2020-12-26 15:19 UTC, dadaa commented on src/reducer.ts
>    map?: Map;
むしろ map を初期化してしまうと、無駄な情報が減りそうです。
map? を map にしてください。

2020-12-26 15:19 UTC, dadaa commented on src/reducer.ts
> +  defaultZoom: 12,
そして
```
map: { 
  defaultZoom: 12,
}
```
などと初期化するのはどうでしょうか？
おそらくは、
https://github.com/telepresence-platform/cocosoco/blob/dev/src/types.ts#L2
でエラーが出ると思うので、
key?: string;
にしていただければ。

2020-12-26 15:30 UTC, nboufSD commented
ありがとうございます！
また明日修正させて頂きます！

2020-12-27 05:46 UTC, nboufSD commented on src/actions.ts
> +      dispatch(InitializeMapPropsAction({ key: mapkey }));
確かに！！
修正しました！

2020-12-27 05:50 UTC, nboufSD commented on src/actions.ts
> +    dispatch(InitializeMapLocationAction.started(params));
確かにここでdispatchする必要はないですね…
削除しました！

2020-12-27 06:08 UTC, nboufSD commented on src/reducer.ts
>    map?: Map;
修正しました！

2020-12-27 06:08 UTC, nboufSD commented on src/actions.ts
> +      InitializeMap(dispatch, getState);
latとlngは0で初期化することにしました！

2020-12-27 06:08 UTC, nboufSD commented on src/actions.ts
> +    dispatch(InitializeMapLocationAction.started(params));
削除しました！

2020-12-27 06:10 UTC, nboufSD commented on src/reducer.ts
> +  defaultZoom: 12,
MapPanelでGoogleMapAPIに入れるときにエラーが出るので、
MapPanel内でif文を挟んで、回避しています！

2020-12-27 07:07 UTC, nboufSD commented
InitializeMapが、自分がPresenterの時にのみ作動する様にしていたのですが、
トグルボタンで始動させることになったので（トグルボタンはPresentterにしか現れない）、Presenterかどうかを判断するif文を消しました。
さらに、navigator.geolocation.getCurrentPositionが作動していない様だったので、そこも修正しました。

2020-12-27 07:46 UTC, dadaa requested changes
レビューしましたー
確認ください

2020-12-27 07:46 UTC, dadaa commented on src/actions.ts
> +    dispatch(InitializeMapLocationAction.started(params));
InitializeMapLocationAction 関係全部削除して良いかと思います。

2020-12-27 07:46 UTC, dadaa commented on src/actions.ts
> -      });
ロジック的にこちらの方が正しいです。
で、`dispatch(InitializeMapAction.done({ result, params }));` の代わりに、
```
    dispatch(
      OnMapLocationChangedAction({
        lat,
        lng,
      })
    );
 ```
を使えば良いと思います。
また、自分がプレゼンタの場合は、current poisition を皆に伝える必要があると思います。

2020-12-27 07:46 UTC, dadaa commented on src/components/MapPanel.tsx
> +    if (!map.key) {
key だけでなく map.lat と map.lng が 0 の場合も null を返す対象かと思います。

2020-12-27 07:46 UTC, dadaa commented on src/reducer.ts
> +  mapkey?: string;
これはもう使わない？

2020-12-27 07:46 UTC, dadaa commented on src/reducer.ts
このあたりに
```
const map = Object.assign({}, state.map, { key: mapkey });
```
として、
```
    return Object.assign({}, state, {
      audiences,
      localPeer,
      localStream,
      map,
      room,
    });
```
などとするのはいかがでしょう。

2020-12-27 07:46 UTC, dadaa commented on src/reducer.ts
> +    });
実質的に `OnMapLocationChangedAction` と同じアクションなので、これは要らないと思っております。

2020-12-27 07:50 UTC, dadaa reviewed
あともう一つ。
location を mute にした場合は watchPosition による位置情報の取得を解除しておきたいです。
`geolocation.clearWatch()`
が使えると思いますので、これもやってしまいましょう。
ドキュメントは以下になります。
https://developer.mozilla.org/ja/docs/Web/API/Geolocation/clearWatch

2020-12-27 11:27 UTC, nboufSD commented on src/actions.ts
> -      });
修正しました！！
今の修正版はcurrent positionを伝えれていると思っていたのですが、伝えられていないでしょうか…？

2020-12-27 11:28 UTC, nboufSD commented on src/components/MapPanel.tsx
> +    if (!map.key) {
修正します！

2020-12-27 11:29 UTC, nboufSD commented on src/reducer.ts
> +  mapkey?: string;
すみません！
削除しました！

2020-12-27 11:32 UTC, nboufSD commented on src/reducer.ts
そちらでいかせて頂きます！

2020-12-27 11:48 UTC, nboufSD commented on src/actions.ts
> -      });
すみません！勘違いしてました！
修正しました！

2020-12-27 11:49 UTC, nboufSD commented on src/reducer.ts
> +    });
見直したらその通りでした！
削除しました！

2020-12-27 16:04 UTC, dadaa requested changes

2020-12-27 16:04 UTC, dadaa commented on src/actions.ts
> +  );
ここのコードは 370 行目からのものとほぼ同じなので、共通関数を作ってそれを呼ぶようにしたいです。

2020-12-27 16:04 UTC, dadaa commented on src/components/MapPanel.tsx
> +    if (!map.key || map.lat === 0 || map.lng === 0) {
ここも watchId が無ければ。という条件に変更しましょうか。

2020-12-27 16:06 UTC, dadaa commented on src/actions.ts
> +export const OnMapLocationWatchIdAction = actionCreator<{
OnMapLocationWatchedAction かな？

2020-12-27 16:11 UTC, nboufSD commented
レビューありがとうございます！
修正します！

2020-12-27 16:17 UTC, nboufSD commented on src/actions.ts
> +      if (isEnabled === false && watchId) {
修正します!

2020-12-27 16:18 UTC, nboufSD commented on src/actions.ts
> +        navigator.geolocation.clearWatch(watchId);
ありがとうございます！
OnMapLocationWatchIdAction({ watchId: null });
でnullをセットします！

2020-12-27 16:21 UTC, nboufSD commented on src/actions.ts
> +      if (state.map.lat === 0 && state.map.lng === 0) {
変更します！

2020-12-27 16:23 UTC, nboufSD commented on src/actions.ts
> +        InitializeMap(dispatch, getState);
確かにInitializeMapはちょっと不適切な名前かもしれませんね…
ActivateMapに変更します！

2020-12-27 16:33 UTC, nboufSD commented on src/actions.ts
> +  );
function updateLocation(
  dispatch: ThunkDispatch<TStore, void, AnyAction>,
  room: SFURoom | MeshRoom,
  lat: number,
  lng: number,
  ) {
  room.send({
    type: "location-changed",
    lat,
    lng,
  });
  dispatch(
    OnMapLocationChangedAction({
      lat,
      lng,
    })
  );
}

という共通関数を作りました！

2020-12-27 16:34 UTC, nboufSD commented on src/components/MapPanel.tsx
> +    if (!map.key || map.lat === 0 || map.lng === 0) {
変更しました！

2020-12-27 16:37 UTC, nboufSD commented on src/actions.ts
> +export const OnMapLocationWatchIdAction = actionCreator<{
その名前でいかして頂きます！

2020-12-27 19:05 UTC, dadaa commented on src/components/MapPanel.tsx
> +    if (!map.key || (!isPresenterMapEnabled && !map.watchId)) {
ここも間違っていました。ごめんなさい。
watchId を見る必要がなさそうです。
なぜなら isPresenterMapEnabled はプレゼンターの状態なのに対して、watchId は自分の状態なので、自分以外の人がプレゼンターの場合は、確実に watchId が無い状態になります。
元の通り、
`if (!map.key)`
の評価だけで良さそうです。

2020-12-28 02:51 UTC, nboufSD commented on src/components/MapPanel.tsx
> +    if (!map.key || (!isPresenterMapEnabled && !map.watchId)) {
すみません！間違えてました！
classNameの定義と共に修正します！

2020-12-28 03:04 UTC, dadaa requested changes
ありがと！
あとは細かいところだけです！

2020-12-28 03:04 UTC, dadaa commented on src/actions.ts
> +  if (room) {
nit: 一行開けてくださいませ。

2020-12-28 03:04 UTC, dadaa commented on src/actions.ts
> +    if (amIPresenter(state) && room) {
上の state の存在確認も合わせて評価してしまったらどうでしょう？
`if (state && amIPresenter(state) && room) {`

2020-12-28 03:04 UTC, dadaa commented on src/actions.ts
> +    if (store.state.map) {
この評価はもう要らなくなったはず。

2020-12-28 03:07 UTC, nboufSD commented on src/actions.ts
> +  if (room) {
すいません！修正しました！

2020-12-28 03:08 UTC, nboufSD commented on src/actions.ts
> +    if (amIPresenter(state) && room) {
確かに…修正しました！

2020-12-28 03:08 UTC, nboufSD commented on src/actions.ts
> +    if (store.state.map) {
すいません！削除しました！

2020-12-28 03:20 UTC, dadaa approved these changes
良さそうな気がします！

2020-12-28 13:01 UTC, merged