fixed #55
telepresence-platform/cocosoco pull request #61
Opened 2020-12-29 06:29 UTC by nboufSD

2020-12-29 22:27 UTC, dadaa requested changes

2020-12-29 22:27 UTC, dadaa commented on src/actions.ts
> -export function selectPeer(peerId: string) {
実はギャラリービューの実装でこの関数を使っている&&今のところ実績のあるコード&&まだプレゼンターの選択方法は変わる可能性がある、ということを考慮して、この関数に自分の peerId を渡すように変更できたりしますか？

本当は今回してもらった修正のように、今必要なモノだけに削ぎ落とすのは、ベリー良いアプローチです！
基本的にはその路線が正しいと思っておりますが、今回はちょっと特別に。

2020-12-29 22:27 UTC, dadaa commented on src/components/PresenterSelected.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
なんか良いアイコンないかなぁ
プレゼンターになるってなんだろうね。
Google slide とかの"プレゼンを開始する"だと、再生的なアイコンですけど、合うかな？？

ちなみに以下は、Mozilla が公開している自由に使えるアイコンです。
https://design.firefox.com/icons/viewer/#

2020-12-29 22:27 UTC, dadaa commented on src/components/PresenterSelected.tsx
> +class PresenterSelected extends React.PureComponent<IProps> {
いま、他のボタン群は、{対象}{やることのing} の名前になっているので、それにならえば `PresenterSelecting` ?

2020-12-29 22:27 UTC, dadaa commented on src/components/AudienceItem.tsx
> -import { connect } from "react-redux";
この issue は、あくまで "プレゼンターになるボタンを付ける" なので、まだ AudienceItem などの修正は入れなくて良いです。

2020-12-30 02:02 UTC, nboufSD commented
レビューありがとうございます！
また修正します！

2020-12-30 08:48 UTC, nboufSD commented on src/actions.ts
> -export function selectPeer(peerId: string) {
すみません！もうアイコンをクリックして選択する方法はなくなると思って消してしまいました！
修正しました！

2020-12-30 08:50 UTC, nboufSD commented on src/components/PresenterSelected.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
良いと思います！
個人的には、Photon IconsのNotificationも良いと思いました！

2020-12-30 08:51 UTC, nboufSD commented on src/components/PresenterSelected.tsx
> +class PresenterSelected extends React.PureComponent<IProps> {
すいません！その名前に変更します！

2020-12-30 08:52 UTC, nboufSD commented on src/components/AudienceItem.tsx
> -import { connect } from "react-redux";
元に戻しました！

2020-12-30 09:29 UTC, dadaa requested changes
ありがとーございます
レビューいたしましたー

2020-12-30 09:29 UTC, dadaa commented on src/components/PresenterSelecting.css
> +.presenter-selected {
nit: presenter-selecting

2020-12-30 09:29 UTC, dadaa commented on src/components/PresenterSelecting.css
> +.presenter-selected__image {
同様に。

2020-12-30 09:29 UTC, dadaa commented on src/components/PresenterSelecting.css
> +  height: 100%;
これは .room の大きさを引き取ってしまうので、めちゃめちゃ大きい指定になり、結果的に常に max-width, max-height が適用され 100px になると思います。
以下はギャラリーボタンの css ですが、他のミュートボタンなどのスタイルと整合性が合うように書いていますので、参考にしてください。
https://github.com/telepresence-platform/cocosoco/pull/62/files#diff-d38ab67eb84ac78e1199be93ca9347ac1a9c6c74ae277d0ff151593708511810R1-R14

2020-12-30 09:29 UTC, dadaa commented on src/components/PresenterSelecting.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
結局 P で行く？
@yogurt0713 どう思います？

2020-12-30 09:29 UTC, dadaa commented on src/components/PresenterSelecting.tsx
> +  presenter?: Member;
使ってなさそうです。

2020-12-30 09:29 UTC, dadaa commented on src/components/PresenterSelecting.tsx
> +    console.log("OK");
削除してくださいまし。

2020-12-30 09:53 UTC, nboufSD commented on src/components/PresenterSelecting.css
> +.presenter-selected {
すいません！修正しました！

2020-12-30 09:53 UTC, nboufSD commented on src/components/PresenterSelecting.css
> +.presenter-selected__image {
すいません！修正しました！

2020-12-30 09:57 UTC, nboufSD commented on src/components/PresenterSelecting.css
> +  height: 100%;
ありがとうございます！！

2020-12-30 09:57 UTC, nboufSD commented on src/components/PresenterSelecting.tsx
> +  presenter?: Member;
すみません！削除します！

2020-12-30 09:59 UTC, nboufSD commented on src/components/PresenterSelecting.tsx
> +  presenter?: Member;
すみません！削除しました！

2020-12-30 09:59 UTC, nboufSD commented on src/components/PresenterSelecting.tsx
> +    console.log("OK");
すみません！削除しました！

2020-12-30 12:56 UTC, dadaa requested changes

2020-12-30 12:56 UTC, dadaa commented on src/components/PresenterSelecting1.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
このファイルは要らなそうです。

2020-12-30 12:56 UTC, dadaa commented on src/components/PresenterSelecting.tsx
> +          alt="select presenter"
これ文言微妙っすねぇ。`Be the presenter` とかの方が正しい??

2020-12-30 13:25 UTC, nboufSD commented on src/components/PresenterSelecting1.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
すみません！消し忘れていました！！

2020-12-30 13:25 UTC, nboufSD commented on src/components/PresenterSelecting.tsx
> +          alt="select presenter"
それでいかしていただきます！！

2020-12-30 14:07 UTC, dadaa requested changes

2020-12-30 14:07 UTC, dadaa commented on src/components/PresenterSelecting.css
> +  left:120px;
120px はスマートフォンに対しては開けすぎな気がします。
以下のように 16px で統一しておきましょう。
https://github.com/telepresence-platform/cocosoco/blob/dev/src/components/ToolList.css#L4-L6

2020-12-30 14:35 UTC, nboufSD commented on src/components/PresenterSelecting.css
> +  left:120px;
承知しました！

2020-12-30 15:05 UTC, dadaa approved these changes
コードサイドは大丈夫です！
おつかれ〜〜

2020-12-31 02:11 UTC, yogurt0713 commented
動作確認いたしました

2021-01-02 13:17 UTC, merged