マップのトグル処理について
telepresence-platform/cocosoco pull request #7
Opened 2020-10-17 12:44 UTC by nboufSD

2020-10-18 00:12 UTC, dadaa requested changes
どうもありがとうございます！ほぼほぼ LGTM でございます！
いくつか変更してもらいたいこと、確認したいことがありましたので、コメントをみてください。

2020-10-18 00:12 UTC, dadaa commented on src/components/MapMuting.svg
> +
この svg って自分で作ったものです？
もしそうだとしたら、すごい！ありがとうございます！

それを前提にすると、この上のコメントは削除しましょう。
少し余分な情報も含まれているようなので、以下を参考にできる限り小さくして欲しいです。
https://github.com/telepresence-platform/cocosoco/blob/master/src/components/AudioMuting.svg?short_path=433155e
あと 512px で作られていますけど、実際の用途としては max-width 100px にしているので、128px ぐらいにすると、もう少し情報が少なくなるかもです。
https://github.com/telepresence-platform/cocosoco/blob/master/src/components/ToolItem.css#L4

もしどこかから持ってきたものだとしたら、出典を教えて下さい！

2020-10-18 00:12 UTC, dadaa commented on src/components/MapMuting.svg
> +
あるいは、ピンだけでも十分かもしれないですね。
上岡さんにも確認しましょ。
@yogurt0713 どう思います？

2020-10-18 00:12 UTC, dadaa commented on src/components/MapMuting.tsx
> +        <img src={logo} alt="mute/unmute Map" className="map-muting__image" />
小文字の map で良いかな。

2020-10-18 00:12 UTC, dadaa commented on src/components/MapMutingDisabled.svg
> +<!--?xml version="1.0" encoding="utf-8"?-->
Likewise.

2020-10-18 00:12 UTC, dadaa commented on src/components/ToolList.tsx
> +        </ToolItem>
配置位置も少し考えた方が良いかもです。
この map のミュートはそこまで利用頻度が多くはないのではないかと思うので、このツール群は右端におかれるので、スマホ上でのボタンの押しやすさから考えると [map][camera][audio] の順でも良いかも。
What do you think, @yogurt0713 ?

2020-10-18 03:15 UTC, dadaa commented on src/actions.ts
> +      const localStream = state?.localStream;
`const localStream = state?.localStream;`
だけですね。

2020-10-18 03:19 UTC, nboufSD commented on src/actions.ts
> +      // }
削除しました.

2020-10-18 03:20 UTC, nboufSD commented on src/actions.ts
> +      const localStream = state?.localStream;
質問（相談）なのですが, localStreamの方は削除しても問題なかったのですが,上二つは削除すると下のdispatchの方でエラーを吐いてしまいます. これはreducerファイルのToggleMapMutingActionとかを変更して対処した方がいいのでしょうか？

2020-10-18 03:42 UTC, nboufSD commented on src/components/ToolList.tsx
> +        </ToolItem>
確かにそうですね...

2020-10-18 03:53 UTC, nboufSD commented on src/components/MapMuting.tsx
> +        <img src={logo} alt="mute/unmute Map" className="map-muting__image" />
修正しました.

2020-10-18 03:53 UTC, nboufSD commented on src/components/MapMuting.svg
> +
すいません！
これはとりあえず他から持ってきたものです！

ライセンスを読む限り, 加工(サイズ変更など)しても大丈夫とは思いますが, どうしましょう？
出典: https://icooon-mono.com/10984-%e7%9b%ae%e7%9a%84%e5%9c%b0%e3%82%a2%e3%82%a4%e3%82%b3%e3%83%b34/

2020-10-18 04:14 UTC, dadaa commented on src/actions.ts
> +      const localStream = state?.localStream;
あー、ごめんなさい。
`const localStream = state?.localStream;`
だけで大丈夫です。

2020-10-18 04:21 UTC, dadaa commented on src/components/MapMuting.svg
> +
ピンだけのイメージの方が良いか、ちょっと @yogurt0713 にも確認してから考えましょう！

2020-10-18 04:21 UTC, dadaa commented on src/components/ToolList.tsx
> +        </ToolItem>
これも @yogurt0713 に確認しましょう

2020-10-18 05:50 UTC, yogurt0713 requested changes

2020-10-18 05:50 UTC, yogurt0713 commented on src/components/MapMuting.svg
> +
こちら、ライセンスの無い外部のアイコンであれば、使わない方がいいかも。アイコンが邪魔にならない程度にレイアウトのデザインがされているのが重要なので、ピンだけでも意味は通じるので良いかと思いますので、シンプルなピンアイコンを藤本くんにデザインして頂いて使用するのはどうでしょう？

2020-10-18 05:50 UTC, yogurt0713 commented on src/components/ToolList.tsx
> +        </ToolItem>
[map][camera][audio]の順番が良いと思いますー

2020-10-18 12:28 UTC, nboufSD commented on src/actions.ts
> +      const localStream = state?.localStream;
すいません！
上のコメントを見逃していました！
ありがとうございます.

2020-10-18 12:29 UTC, nboufSD commented on src/components/MapMuting.svg
> +
やってみます！
ありがとうございます！

2020-10-18 12:29 UTC, nboufSD commented on src/components/ToolList.tsx
> +        </ToolItem>
承知しました！

2020-10-19 09:52 UTC, dadaa requested changes

2020-10-19 09:52 UTC, dadaa commented on src/components/MapMuting.svg
> +	 y="0px" viewBox="0 0 128 128" style="enable-background:new 0 0 128 128;" xml:space="preserve">
ごめんなさい。他のアイコンとの整合性をもたせるために 16 x 16 で作り直していただいても良いでしょうか？
で、vector-effect="non-scaling-stroke" stroke-width="1" も他と合わせたいと思います。
以下の svg のコードをご参考ください。

https://github.com/telepresence-platform/cocosoco/blob/master/src/components/CameraSwitching.svg?short_path=5c5cde5

2020-10-19 09:52 UTC, dadaa commented on src/components/MapMuting.svg
> +<!-- Generator: Adobe Illustrator 24.3.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
削除しても良さそうです。

2020-10-19 09:52 UTC, dadaa commented on src/components/MapMuting.svg
> +<svg version="1.1" id="レイヤー_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
https://github.com/telepresence-platform/cocosoco/blob/master/src/components/CameraSwitching.svg?short_path=5c5cde5 などを参考に、必要のない id や x, y などは削除したいです。

2020-10-19 09:52 UTC, dadaa commented on src/components/MapMuting.svg
> +<circle class="st2" cx="143" cy="11.6" r="0.3"/>
この circle は意味が無い感じ？
だとしたら、削除しましょー！

2020-10-19 10:24 UTC, nboufSD commented on src/components/MapMuting.svg
> +	 y="0px" viewBox="0 0 128 128" style="enable-background:new 0 0 128 128;" xml:space="preserve">
承知いたしました！

2020-10-19 10:24 UTC, nboufSD commented on src/components/MapMuting.svg
> +<!-- Generator: Adobe Illustrator 24.3.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
承知いたしました！

2020-10-19 10:25 UTC, nboufSD commented on src/components/MapMuting.svg
> +<svg version="1.1" id="レイヤー_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
承知いたしました！

2020-10-19 10:25 UTC, nboufSD commented on src/components/MapMuting.svg
> +<circle class="st2" cx="143" cy="11.6" r="0.3"/>
確認してみて, 意味がなさそうなら削除します！

2020-10-20 04:47 UTC, dadaa approved these changes
どうもありがとうございました〜！

2020-10-20 04:47 UTC, dadaa commented on src/components/MapMuting.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
ずいぶんスッキリ！
ありがとうございました！

2020-10-20 04:48 UTC, dadaa commented
@yogurt0713 のレビューが approval だったらマージします！

2020-10-20 05:43 UTC, yogurt0713 approved these changes

2020-10-20 05:49 UTC, merged

2020-10-20 08:38 UTC, nboufSD commented on src/components/MapMuting.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
こちらこそ, ご指導ありがとうございました！