fixed #57
telepresence-platform/cocosoco pull request #73
Opened 2021-01-06 09:26 UTC by nboufSD

2021-01-06 09:45 UTC, dadaa requested changes
ありがとうございます！
コードだけ拝見したのですが、おそらく、ちょっとだけずれちゃってるような気がします。
この issue でやりたいことは、
１．*自分がプレゼンターであるかは関係なく* AudienceList の中でプレゼンターになっている AudienceItem を一番左に表示する。
２．AudienceList の中でプレゼンター以外の AudienceItem を小さくする。
だと思います。
なので、作りとしては全て AudienceList, AudienceItem で実現できると思います。
また、順番を変えたい場合は、FlexBox の order などで実現できそうな気がします。
https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items

2021-01-06 09:52 UTC, yogurt0713 commented
プレゼンターの位置ですが，足跡に並列した位置（いままでのy座標位置）で問題ないように思います．
いま，プレゼンターになると足跡の上に配置されているようです．

2021-01-06 11:33 UTC, nboufSD commented
すみません！勘違いしてました！
また修正します！

2021-01-09 12:22 UTC, dadaa commented
Duplicate of #74.

2021-01-09 12:22 UTC, closed without merging