fixed #77
telepresence-platform/cocosoco pull request #84
Opened 2021-01-09 03:39 UTC by nboufSD

まだ修正が終わっていません！すみません！

何故かflexを指定すると二段組になってしまいます…
もしかしたら、足跡アイコンがbutton属性を持っているのが原因かな？とも思って、
足跡アイコンの部分をdivで括ってもみたのですがうまくいきません…
[https://qiita.com/ln-north/items/4638ca6f645cf6d69a75](url)

flexを指定するときに気にしなければいけない点は有りますでしょうか…？

2021-01-09 10:16 UTC, nboufSD commented
修正しました！
丸枠（枠線の中が透過している）を border-radius: 50%;で実装しようとしたのですが、大きさを合わせるのが難しかったので同じ大きさの円を表示してます！すみません！

2021-01-09 10:29 UTC, yogurt0713 commented
人数表示は＋はいらなくて数字だけでよいかと思います．
表示位置はissueにあるように円の中にした方がすっきりしそうです

2021-01-09 10:39 UTC, nboufSD commented
修正しました！
色合いとかのデザインは大丈夫でしょうか？

2021-01-09 13:57 UTC, yogurt0713 commented
確認いたしました．
足跡ボタンがプレゼンターアリ，ナシの時に位置が移動してしまうのがちょっと気になるので
足跡ボタンは固定で，プレゼンターアイコンが表示される〇を前のデザインのように最初は空の状態で
表示してプレゼンターが出てきた時に〇にアイコンを表示というのはどうでしょうか？

2021-01-09 14:22 UTC, dadaa requested changes
ありがとうございますー
レビューしましたー

2021-01-09 14:22 UTC, dadaa commented on src/components/AudienceList.css
> +  visibility: hidden;
この変更だけして、あとの AudienceItem.css と AudienceList.css  の変更は元に戻しましょう。

2021-01-09 14:22 UTC, dadaa commented on src/components/AudienceNumbers.css
> +  z-index: 4;
4まで大きな指定は必要ですか？

2021-01-09 14:22 UTC, dadaa commented on src/components/AudienceNumbers.css
> +  text-align: center;
この２つは要らない？

2021-01-09 14:22 UTC, dadaa commented on src/components/AudienceNumbers.css
> +  background-color: red;
できれば、
https://design.firefox.com/photon/visuals/color.html
から色を選んでいただきたく。

2021-01-09 14:22 UTC, dadaa commented on src/components/MapPanel.css
> -
この css の変更は要らなそうです。

2021-01-09 14:22 UTC, dadaa commented on src/components/PresenterIcon.css
> +  background-color: aliceblue;
色はできるだけ、
https://design.firefox.com/photon/visuals/color.html
からプリーズ。

2021-01-09 14:22 UTC, dadaa commented on src/components/PresenterIcon.tsx
> +      <li className="presenter-item">
li はリストのアイテムを表すので、ここでは合わない気がします。

2021-01-09 14:22 UTC, dadaa commented on src/components/PresenterIcon.tsx
> +      <li className="presenter-item">
presenter-item--Nonselected よりは presenter-item--no-presenter とかかな？
これも同じ要素に入れてたら良いような気がします。
```
const className = "presenter-item" + (presenter ? "" : "presenter-item--no-presenter");
return <span className={className}>
  presenter ? <img ...> : null
</span>
```
テストしていないけど、こんな感じに書けますかね?

2021-01-09 14:22 UTC, dadaa commented on src/components/Room.css
> +  flex-wrap: wrap-reverse;
なんで reverse ?

2021-01-09 14:22 UTC, dadaa commented on src/components/Room.tsx
> +          <PresenterIcon />
少なくともこれだと、なにかの修正のおりに位置が簡単にずれちゃう気がします。
なので、PresenterIcon の中で AudienceNumbers を表示すると良いような気がします。

2021-01-10 09:56 UTC, nboufSD commented on src/components/AudienceList.css
> +  visibility: hidden;
修正しました！

2021-01-10 09:57 UTC, nboufSD commented on src/components/AudienceNumbers.css
> +  z-index: 4;
iPhoneで行った場合に4ぐらいがちょうど良さそうだったので4にしてます！

2021-01-10 09:59 UTC, nboufSD commented on src/components/AudienceNumbers.css
> +  text-align: center;
要らなかったです！削除します！

2021-01-10 10:03 UTC, nboufSD commented on src/components/AudienceNumbers.css
> +  z-index: 4;
すいません！勘違いしてました！
1に修正しました！

2021-01-10 10:03 UTC, nboufSD commented on src/components/AudienceNumbers.css
> +  background-color: red;
ありがとうございます！
#ff0039にしました！

2021-01-10 10:05 UTC, nboufSD commented on src/components/MapPanel.css
> -
元々のcssでクラス間の改行が入っていなかったので改行を入れたのですがよくなかったでしょうか…？
（こういう場合は別issueにした方がやはり良い感じですか？）

2021-01-10 10:06 UTC, nboufSD commented on src/components/PresenterIcon.css
> +  background-color: aliceblue;
#f9f9faにしました！

2021-01-10 10:07 UTC, nboufSD commented on src/components/PresenterIcon.css
> +  background-color: aliceblue;
#f9f9faにしました！

2021-01-10 10:08 UTC, dadaa commented on src/components/MapPanel.css
> -
別 issue で！

2021-01-10 10:10 UTC, nboufSD commented on src/components/MapPanel.css
> -
承知しました！

2021-01-10 10:27 UTC, nboufSD commented on src/components/PresenterIcon.tsx
> +      <li className="presenter-item">
ありがとうございます！！
いけました！

2021-01-10 10:29 UTC, nboufSD commented on src/components/Room.css
> +  flex-wrap: wrap-reverse;
前のバージョンで数字を二段目に表示してた名残です！
削除しました！

2021-01-10 10:30 UTC, nboufSD commented on src/components/Room.css
> +  flex-wrap: wrap-reverse;
align-itemsも削除しました！

2021-01-10 10:33 UTC, nboufSD commented on src/components/Room.tsx
> +          <PresenterIcon />
ありがとうございます！
修正したのですが、正しく修正できているか自信がないので確認お願いします！

2021-01-10 10:46 UTC, dadaa approved these changes
ソースコード的にはいいかと思いますー

2021-01-10 10:46 UTC, dadaa commented on src/components/PresenterIcon.tsx
> +      <>
おおお。もしかしてこれで fragment になる？？

2021-01-10 10:47 UTC, yogurt0713 reviewed
iphone safariでストリーミングがフリーズorカメラ画像が見えないエラーがおこります

2021-01-10 10:54 UTC, nboufSD commented on src/components/PresenterIcon.tsx
> +      <>
レビューありがとうございます！
この前教えていただいたReactのページに記述があったので使ってます！
[https://ja.reactjs.org/docs/fragments.html](url)

2021-01-10 10:57 UTC, nboufSD commented
上岡先生のレビューについてですが、僕の方でも確認できました…

2021-01-10 12:42 UTC, dadaa approved these changes

2021-01-10 12:45 UTC, yogurt0713 approved these changes

2021-01-10 12:46 UTC, merged