fixed #79
telepresence-platform/cocosoco pull request #85
Opened 2021-01-11 10:54 UTC by nboufSD

アニメーションの終了と数字の更新の同期が行えていません！
数字の更新をsetTimeoutで遅延させようとしたのですが、うまく出来ません…
componentDidMount()をとかを利用するのかとも思うのですが、よく分からなかったです…
ご指導をお願いしたいです！

2021-01-16 07:39 UTC, yogurt0713 approved these changes
確認させていただきましたー

2021-01-16 09:05 UTC, dadaa requested changes
おつかれさまです！

icon-updated が事実上誰かが入ってきたときに来るイベントなので、これと同じタイミングが使えるとすると、icon-added は特に送らなくても良いのでは？
https://github.com/telepresence-platform/cocosoco/blob/dev/src/actions.ts#L512

とすると、SetIconAction は不必要で、なにかやるのであれば、ParticipateAction でやってしまえば良いかと思います。

2021-01-16 09:05 UTC, dadaa commented on src/reducer.ts
> +  icons: Member[];
icons は、あまりにも汎用で、何を表したいか良くわからないっすねぇ、、
しかも icon なのに、Member だし、もう少しわかりやすい名前にした方が良いかもです。

たとえば、新規参入者(たち)として、 newcomers とかはどうでしょう。
で、AddIcon とかも、AddNewcomer とか。

onStream と item-updated のアイコンデータ、両方が揃ったときに、初めて AddNewcomer() が呼ばれるようにして、AddNewcomer の中ではじめて audiences に追加する方が、データがキレイに保てそうだし、パスを一つに絞れてバグの発生源を少なくできそうです。
これは別 issue で良いと思いますけど、そっちをさきにやった方が良いかね？どう思います？

2021-01-16 10:57 UTC, nboufSD commented on src/reducer.ts
> +  icons: Member[];
レビューありがとうございます！
結構Like.tsxのコードを参考にしているのですが、Likeと違ってすでにあるデータ(dataURL)を使用するため、その分もっと簡単にかけそうな感じはありつつも、うまく書けずに今回の修正になったのが現状です。
自分的には先にコードをきれいにしてから修正を行いたいと思うのですが、ちょっとまだレビューしていただいた内容がイメージできていません…

SetIconActionに関連する部分を削除して、audienceに直接入れたアイコンを取り出すみたいなイメージなのですが大丈夫でしょうか？

onStream と item-updated のアイコンデータ、両方が揃ったときというのは、最初の画面でparticipateボタンをクリックしてデータがreducerに送られた時と考えても大丈夫でしょうか？

2021-02-06 04:26 UTC, nboufSD commented
修正したので、確認をお願いします。

newcomersは、Newcomerという型を別に作って宣言しています。
（以前はMemberを使用していましたが、streamは使わない？と思ってpeerIdとdataURLのみのNewcomerを作りました。）

また、参加アニメーションが終わった後に、参加者人数を増やすという処理なのですが、
今のところ結構微妙なタイミングなので、それに対する特別な処理は行っていません。

もし、しっかりとアニメーションが終わったタイミングで参加者人数を増やすとした場合、
audinecesのように、newcomersを参加者ごとの値を持つ配列にすることが必要なのかなと思っています。

今は、removeの際にnewcomersの初期化を行ってアイコンを消しているのですが、これをdataURL: null　のようにして消すようにし、配列を初期化しないようにしておく。
そして、Newcomer型に isFinAnime: boolean のようなアニメーションが終了した時にフラグを立てる変数を用意しておき、newcomersのisFinAnime === true の数を参加者人数とするようにする。

このようなことが考えられるのですが、どうでしょうか…？
ただ、newcomerをaudiencesのようにするとなると、roomを利用しないといけなくなるのでコードが長くなるかなとも思っています。

2021-02-06 04:42 UTC, dadaa requested changes
ありがとうございます。
レビューいたしました

2021-02-06 04:42 UTC, dadaa commented on src/actions.ts
> +      dispatch(setNewcomer(dataURL, localPeer.id));
自分は出さなくても良いと思います。
が、 @yogurt0713 どう思いますか？

2021-02-06 04:42 UTC, dadaa commented on src/actions.ts
> +      clearTimeout(newcomerTimerMap.get(peerId));
Pointing 指さしアクションの場合、同じ人が短時間に複数回クリックされるような場面が想像されるため、前回のクリックによる削除タイマーを無視するために map に set していました。
AddNewcomoer の場合は、一つの peerId に対して一回だけしか呼ばれないはずなので、map で管理する必要がないと思います。

2021-02-06 04:42 UTC, dadaa commented on src/actions.ts
> +        () => dispatch(RemoveNewcomerAction({})),
削除の際に peerId が必要なのでは？

2021-02-06 04:42 UTC, dadaa commented on src/actions.ts
> +        state.room?.send({ type: "newcomer-added", peerId, dataURL });
AddAudience を呼ぶタイミングが、AddNewcomer になるタイミングだと思うので、改めて "newcomer-added" を送る理由はないと思います。

2021-02-06 04:42 UTC, dadaa commented on src/components/InterAudienceIcon.tsx
> +class InterAudienceIcon extends React.PureComponent<IProps> {
かたや Newcomer かたや InterAudience なので、名前を合わせてほしいです。

2021-02-06 04:42 UTC, dadaa commented on src/reducer.ts
> +  newcomers: Newcomer[];
AddAudiece のタイミングで、このアニメーションをすれば良いと思うので、Member をそのまま使えば良いと思います。

2021-02-06 04:45 UTC, yogurt0713 commented on src/actions.ts
> +      dispatch(setNewcomer(dataURL, localPeer.id));
自分は出さなくてよいとおもいます．既知なので

2021-02-06 07:23 UTC, nboufSD commented on src/actions.ts
> +      dispatch(setNewcomer(dataURL, localPeer.id));
承知しました！

2021-02-06 07:35 UTC, nboufSD commented on src/actions.ts
> +      clearTimeout(newcomerTimerMap.get(peerId));
ありがとうございます！修正しました！

2021-02-06 07:44 UTC, nboufSD commented on src/actions.ts
> +        () => dispatch(RemoveNewcomerAction({})),
配列ごと削除していたので、peerIdは不要かなと思っていたのですが（新規参加者アイコンはフェードアウトで消していたので）、やはりコード的にきれいになるようにpeerIdで消すようにします。

2021-02-06 09:52 UTC, nboufSD commented on src/actions.ts
> +        state.room?.send({ type: "newcomer-added", peerId, dataURL });
修正しました！

2021-02-06 09:56 UTC, nboufSD commented on src/components/InterAudienceIcon.tsx
> +class InterAudienceIcon extends React.PureComponent<IProps> {
すいません！修正しました。

2021-02-06 10:00 UTC, nboufSD commented on src/reducer.ts
> +  newcomers: Newcomer[];
これはnewcomersではなく、audiencesのdataURLを直接表示させた方が良いのかなと思ったのですが、どうでしょうか？

2021-02-06 11:06 UTC, dadaa requested changes

2021-02-06 11:06 UTC, dadaa commented on src/components/InterNewcomer.tsx
> +class InterNewcomer extends React.PureComponent<IProps> {
配列を扱うコンポーネントが単数形なのは違和感があります。
他のコンポーネントと一貫性を保つために、NewcomerList, NewcomerItem のようにしてはどうでしょうか。
例：
* List https://github.com/telepresence-platform/cocosoco/blob/dev/src/components/AudienceList.tsx
* Item https://github.com/telepresence-platform/cocosoco/blob/dev/src/components/AudienceItem.tsx

2021-02-06 11:38 UTC, nboufSD commented on src/actions.ts
> +    }
すみません！削除しました。

2021-02-06 11:38 UTC, nboufSD commented on src/actions.ts
> +);
これもです！すみません。

2021-02-06 11:41 UTC, nboufSD commented on src/components/InterNewcomer.css
> +}
ありがとうございます！修正しました。

2021-02-06 11:44 UTC, nboufSD commented on src/components/InterNewcomer.tsx
> +class InterNewcomer extends React.PureComponent<IProps> {
NewcomerListでいかせて頂きます！

2021-02-06 11:59 UTC, dadaa commented on src/components/NewcomerList.tsx
> +    return <section> {this._renderNewcomers()} </section>;
-renderNewComer の中身はここに展開しても良さそうです。

2021-02-06 12:42 UTC, nboufSD commented on src/components/NewcomerList.tsx
> +    return <section> {this._renderNewcomers()} </section>;
修正しました！

2021-02-06 23:45 UTC, dadaa requested changes

2021-02-06 23:45 UTC, dadaa commented on src/actions.ts
> +      () => dispatch(UpdateAudience({ peerId, stream, dataURL })),
ここでは stream, dataURL を更新する必要はないと思います。
代わりに isNewcomer を明示的にしてあげると、何をしたいのかが明確になりそうです。
`UpdateAudience({ peerId, isNewcomer: false })`

2021-02-06 23:45 UTC, dadaa commented on src/components/NewcomerItem.tsx
> +    return newcomer.peerId !== localPeer?.id ? (
この peer が自分である場合、無駄な div ができてしまいます。
代わりに、NewcomerList の filter で 自分の peer である場合も排除してしまいましょう。

2021-02-06 23:45 UTC, dadaa commented on src/components/NewcomerList.tsx
> +      audience => audience.isNewcomer === true
別のところでも言いましたが、ここで自分のピアは排除しましょう。
それと、if (isNewcomer === true) や if (isNewcomer === false) などは if (isNewcomer)、if (!isNewcomer) で置き換えられます。これまで同様、今後も同じスタイルでいきたいので覚えておいてください。
最終的にここは以下のようになるはずです。
`audience => audience.isNewcomer && audience.peerId !== localPeer.id`

2021-02-06 23:45 UTC, dadaa commented on src/reducer.ts
> +      audience = Object.assign({}, audience, { dataURL, isNewcomer: false });
違うところでも書きましたが、isNewcomer は明示的に指定するようにしましょう。
```
if (isNewcomer !== undefined) {
  audience = Object.assign({}, audience, { isNewcomer });
}
```
か、あるいは全ての分岐をまとめて、
```
stream = stream || audience.stream;
dataURL = dataURL || audience.dataURL;
isNewcomer = isNewcomer !== undefined ? isNewcomer : audience.isNewcomer;
audience = Object.assign({}, audience, { stream, dataURL, isNewcomer });
```
でも良いかと思います。

2021-02-07 03:11 UTC, yogurt0713 reviewed
1．iphoneの4台以上の接続に以下の不具合が見られる
（極端に更新スピードが他のデバイスに比較して遅いのが起因している？）
・iphone（接続済）のみ接続数が異なる（本当は5台接続しているのに4台と表示）ことがある
いつも起こるわけではないのですが，更新遅れなどタイミングの問題のようです．
・iphoneのアニメーションが極端に遅い（4台目以降）

2．新しくルームに入ってきた参加者のアイコンにすでに入っている参加者のアニメーション表現は不要と思いますがいかがでしょうか？

2021-02-09 10:26 UTC, nboufSD commented on src/actions.ts
> +      () => dispatch(UpdateAudience({ peerId, stream, dataURL })),
ありがとうございます！
修正しました！

2021-02-09 10:29 UTC, nboufSD commented on src/components/NewcomerItem.tsx
> +    return newcomer.peerId !== localPeer?.id ? (
下のレビューを参考にして修正しました！

2021-02-09 10:29 UTC, nboufSD commented on src/components/NewcomerList.tsx
> +      audience => audience.isNewcomer === true
すいません！以後気を付けます！

2021-02-09 10:30 UTC, nboufSD commented on src/components/NewcomerList.tsx
> +      audience => audience.isNewcomer === true
修正しました！

2021-02-09 10:32 UTC, nboufSD commented on src/reducer.ts
> +      audience = Object.assign({}, audience, { dataURL, isNewcomer: false });
全ての分岐をまとめる形に修正しました。

2021-02-09 13:48 UTC, dadaa requested changes

2021-02-09 13:48 UTC, dadaa commented on src/components/NewcomerItem.tsx
> +    return newcomer.peerId !== localPeer?.id ? (
Listの方で不必要な newcomer は排除できているので、`newcomer.peerId !== localPeer?.id ? ` の評価は要らなくなるはずです。
とすると、localPeer を持つ必要もなくなるので IProps から排除してください。

2021-02-09 13:48 UTC, dadaa commented on src/components/NewcomerItem.tsx
> +        key={newcomer.peerId}
key 要らないんじゃない？

2021-02-10 01:14 UTC, nboufSD commented on src/components/NewcomerItem.tsx
> +    return newcomer.peerId !== localPeer?.id ? (
そうでした…すいません！
修正しました。

2021-02-10 01:15 UTC, nboufSD commented on src/components/NewcomerItem.tsx
> +        key={newcomer.peerId}
itemの方でkeyを設定する必要はなかったです！
修正しました。

2021-02-10 01:23 UTC, dadaa approved these changes
ありがとー
ソース的には問題ないように思います！

2021-02-14 07:11 UTC, closed without merging