fixed #89
telepresence-platform/cocosoco pull request #90
Opened 2021-01-18 05:45 UTC by nboufSD

修正しました！
Participateした時に、自分のstreamやdataURLは一括で取得できるので、audiencesに直接入れているのですが、大丈夫でしょうか？

2021-01-18 05:54 UTC, nboufSD commented
今気付いたのですが、3人以上？入室する場合、素早く入室しないと3人目のstateのaudiencesが2人分しか更新されない様なのでまた修正します…

2021-01-27 12:24 UTC, dadaa requested changes
ありがとー
レビューしましたので、確認ください。

2021-01-27 12:24 UTC, dadaa commented on src/actions.ts
>    dispatch(AddPeerAction({ peerId: stream.peerId, stream }));
この書き方だと、AddPeerAction も呼んでしまうし、全てが揃ったら AddAudiences も呼んでしまうことになりそうです。なので、この前に評価して、揃っていたら AddAudiences 揃ってなければ AddPeerAction を呼ぶようにすると良いかと思います。

また、このあたりの評価と、足りなけれっば audienceInPreparation に追加、満たされていれば AddAudiences で追加するロジックは、icon-updated でも同様なので、共通の関数にする方が良いと思います。

アクションの名前も、よりわかりやすく、
満たされていれば：AddAudience
満たされていなければ：AddAudienceInPreparation
とすると、スッキリしそうです。

2021-01-27 12:24 UTC, dadaa commented on src/actions.ts
> +}>("ADD_AUDIENCES");
追加される Member は一人なので、単数形が良いと思います。

2021-01-27 12:24 UTC, dadaa commented on src/actions.ts
> +  ) {
どうして最後に追加された人しか調べないの？
ネットワークによってはタイミングがまちまちなので、かならず全てが想像通りの順番でくるとは限りません。
よって audiencesInPreparation から該当する peerId の audience を取得し、まだ無い場合は、AddAudienceInPreparation を、onStream と icon-updated からのデータで全て満たされれば AddAudience を呼ぶようにしてはいかがでしょうか？

2021-01-27 12:24 UTC, dadaa commented on src/reducer.ts
> +    return Object.assign({}, state, { audiences: [...audiences] });
```
return Object.assign({}, state, { audiences: [...state.audiences, { peerId , stream, dataURL }] });
```

2021-01-27 12:24 UTC, dadaa commented on src/reducer.ts
> +  .case(AddAudiences, (state, { audiencesInPreparation }) => {
引数は peerId , stream, dataURL を取るようにしましょう。

また、この内部では、audiencesInPreparation から不必要なデータを取り除く必要があると思います。
あと、このあたりの処理も。
https://github.com/telepresence-platform/cocosoco/blob/dev/src/reducer.ts#L75-L81

2021-01-27 12:25 UTC, dadaa commented on src/actions.ts
>    dispatch(AddPeerAction({ peerId: stream.peerId, stream }));
つまり AddPeerAction と OnIconUpdatedAction は削除で。

2021-01-27 12:46 UTC, nboufSD commented on src/actions.ts
>    dispatch(AddPeerAction({ peerId: stream.peerId, stream }));
上記の様に修正します！
ありがとうございます！

2021-01-27 12:46 UTC, nboufSD commented on src/actions.ts
> +}>("ADD_AUDIENCES");
修正しました！

2021-01-27 12:47 UTC, nboufSD commented on src/actions.ts
> +  ) {
ここなのですが、該当するpeerId（新しく追加された人のpeerId）はどうやって定義すれば良いのでしょうか…？

2021-01-27 12:54 UTC, nboufSD commented on src/actions.ts
> +  ) {
ここなのですが、該当するpeerId（新しく追加された人のpeerId）はどうやって定義すれば良いのでしょうか…？

2021-01-27 12:57 UTC, dadaa commented on src/actions.ts
> +  ) {
onStream からは stream.peerId 、icon-update からは 送られてくる data の peerId がそれに該当すると思います。
https://github.com/telepresence-platform/cocosoco/blob/dev/src/actions.ts#L469
https://github.com/telepresence-platform/cocosoco/blob/dev/src/actions.ts#L516

2021-01-27 14:02 UTC, nboufSD commented on src/actions.ts
> +  ) {
ありがとうございます！
できました！

2021-01-27 14:03 UTC, nboufSD commented on src/reducer.ts
> +    return Object.assign({}, state, { audiences: [...audiences] });
ありがとうございます！！！

2021-01-27 14:04 UTC, nboufSD commented on src/reducer.ts
> +  .case(AddAudiences, (state, { audiencesInPreparation }) => {
AddAudienceの処理に関する修正が終わり次第、そこの修正を行います！
ありがとうございます！

2021-01-27 14:04 UTC, nboufSD commented on src/reducer.ts
> +  .case(AddAudiences, (state, { audiencesInPreparation }) => {
引数のところは修正しました！

2021-01-27 14:10 UTC, nboufSD commented
レビューありがとうございます！
二つのチェックを通過することでactionで完全なaudienceInPreparationを取得することができたのですが、
その後にAddAudienceを通過することが出来ません…（どこかで３度目のチェックポイントが必要？）

2021-01-29 03:21 UTC, dadaa requested changes

2021-01-29 03:21 UTC, dadaa commented on src/actions.ts
> +}>("ADD_ADDAUDIENCEINPREPARATION");
nit: ADD_AUDIENCE_IN_PREPARATION

2021-01-29 03:21 UTC, dadaa commented on src/actions.ts
> +}>("REMOVE_ADDAUDIENCEINPREPARATION");
nit: REMOVE_AUDIENCE_IN_PREPARATION

2021-01-29 03:21 UTC, dadaa commented on src/actions.ts
> +}>("ADD_AUDIENCES");
nit: ADD_AUDIENCE

2021-01-29 03:21 UTC, dadaa commented on src/actions.ts
> +    );
うーん、やっぱ、無駄かなぁ、、
AddAudience で削除しちゃいましょうか？

2021-01-29 03:21 UTC, dadaa commented on src/actions.ts
> +      }
前のコメントにも書きましたけど、この処理はほぼ onStream での処理と同じなので、共通の関数を作ってそこでやるようにしてほしいです。

2021-01-29 03:21 UTC, dadaa commented on src/reducer.ts
> +    );
action 内で全てが満たされたら audience に昇格するように書いてあるし、且つそのルートは onStream と icon-update のどちらかなので、新しく追加する audienceInPreparation が state.audiencesInPreparation に存在することはあり得ないのでは？

2021-01-29 03:32 UTC, nboufSD commented on src/actions.ts
> +}>("ADD_ADDAUDIENCEINPREPARATION");
修正しました！

2021-01-29 03:33 UTC, nboufSD commented on src/actions.ts
> +}>("ADD_AUDIENCES");
修正しました！

2021-01-29 03:41 UTC, nboufSD commented on src/actions.ts
> +    );
AddAudienceにまとめました！

2021-01-29 04:06 UTC, nboufSD commented on src/actions.ts
> +      }
すみません！見逃していました！
共通関数checkAudiencesInPreparationを作成して修正しました！

2021-01-29 04:33 UTC, nboufSD commented on src/reducer.ts
> +    );
どのタイミングで呼ばれるのか自分でもよく分かっていなかったので、この様な書き方になっていました…
コンソールで調べたところ、elseのみにしか流れていなかったので、それに関する修正を行います！
ありがとうございます！

2021-01-29 04:54 UTC, dadaa requested changes

2021-01-29 04:54 UTC, dadaa commented on src/actions.ts
> +function checkAudiencesInPreparation(
updateAudienceInPreparation?
check だと、チェックするだけのように思えるので。

2021-01-29 04:54 UTC, dadaa commented on src/actions.ts
> +  data?: any
peerId, stream, dataURL を引数に。

2021-01-29 04:54 UTC, dadaa commented on src/actions.ts
> +    }
ここもほぼ同じなので共通化したいです。

```
    const audienceInPreparation = state.audiencesInPreparation.find(
      a => a.peerId === data.peerId
    );

    if (audienceInPreparation) {
      stream = stream || audienceInPreparation.stream;
      dataURL = dataURL || audienceInPreparation.dataURL;
    }

    if (stream && dataURL) {
      // AddAudience
    } else {
      // AddAudienceInPreparation
    }
```

2021-01-29 06:43 UTC, nboufSD commented on src/actions.ts
> +function checkAudiencesInPreparation(
updateAudienceInPreparationでいかせてただきます！
ありがとうございます！

2021-01-29 06:49 UTC, nboufSD commented on src/actions.ts
> +  data?: any
修正しました！

2021-01-29 06:59 UTC, nboufSD commented on src/actions.ts
> +    }
ありがとうございます！
コードがかなりきれいになりました！

2021-01-29 07:33 UTC, dadaa requested changes

2021-01-29 07:33 UTC, dadaa commented on src/actions.ts
>  }
if (audience) からここまでの処理も、`updateAudienceInPreparation` の中に移動できそうな気がします。
dispatch(AddAudience({ peerId, stream, dataURL })); した後とか。

2021-01-29 08:28 UTC, nboufSD commented on src/actions.ts
>  }
レビューありがとうございます。
[https://github.com/telepresence-platform/cocosoco/blob/dev/src/actions.ts#L473-L495](url)
ここをupdateAudienceInPreparationの中に入れるということで合ってますか…？

2021-01-29 08:58 UTC, dadaa commented on src/actions.ts
>  }
そうっす。

2021-01-29 10:01 UTC, nboufSD commented on src/actions.ts
>  }
試してみたのですが、どうもうまくいっていません…
onData側でroom.sendさせない様にすることが必要なのだと思いますが、ちょっと理解が追いついていないです…

2021-01-29 11:29 UTC, dadaa commented on src/actions.ts
>  }
何がうまくいっていないかを教えてもらえませんか？

2021-01-29 11:34 UTC, nboufSD commented on src/actions.ts
>  }
`function updateAudienceInPreparation(
  dispatch: ThunkDispatch<TStore, void, AnyAction>,
  state: IState,
  peerId: string,
  stream?: any,
  dataURL?: string
) {
  const audienceInPreparation = state.audiencesInPreparation.find(
    a => a.peerId === peerId
  );

  if (audienceInPreparation) {
    stream = stream || audienceInPreparation.stream;
    dataURL = dataURL || audienceInPreparation.dataURL;
  }

  if (stream && dataURL) {
    dispatch(AddAudience({ peerId, stream, dataURL }));
  } else {
    dispatch(AddAudienceInPreparation({ peerId, stream, dataURL }));
  }
  const audience = state.audiences.find(a => a.peerId === state.localPeer?.id);
  if (audience) {
    state.room?.send({
      type: "icon-updated",
      dataURL: dataURL,
      peerId: peerId,
    });
  }
  // Tell who is a presenter now, to peer joined newly.
  if (state.presenter) {
    state.room?.send({
      type: "peer-selected",
      peerId: state.presenter.peerId,
    });
    state.room?.send({
      type: "location-muted",
      isMapEnabled: state.isPresenterMapEnabled,
    });
    state.room?.send({
      type: "location-changed",
      lat: state.map.lat,
      lng: state.map.lng,
    });
  }
}`

2021-01-29 11:41 UTC, nboufSD commented on src/actions.ts
>  }
Addaudienceの下に変更部分を書くと、
if (stream && dataURL) {〜
に入らなくなってしまいます…

2021-01-29 11:48 UTC, dadaa commented on src/actions.ts
>  }
dispatch(AddAudience({ peerId, stream, dataURL }));
の下は？

2021-01-29 11:51 UTC, nboufSD commented on src/actions.ts
>  }
そこに書くと、Addaudienceを書いてある
if (stream && dataURL) {〜
に遷移しなくなってしまいます…

もしかすると、自分のpeerId,stream,dataURLは
participateした時にそのままaudienceに入れているのが問題かもしれません…

2021-01-29 11:53 UTC, dadaa commented on src/actions.ts
>  }
AddAudienceInPreparation の下は？

2021-01-29 11:54 UTC, dadaa commented on src/actions.ts
>  }
元のコードは、stream が来たときに処理してたので、おそらくこれは動くと思います。

2021-01-30 07:45 UTC, dadaa requested changes
おつかれさま。
あと、ちょっとだけお願いしますー

2021-01-30 07:45 UTC, dadaa commented on src/actions.ts
> +    }
いろいろわかったところで、いよいよこの部分を(はじめの if は抜いて)、
`dispatch(AddAudienceInPreparation({ peerId, stream, dataURL }));`
の前後に持ってこれますかね？
同様に、ここのロジックが少し長いので、shareStatus みたいな関数を作ってひとかたまりにしておくと見やすくなりそうです。

2021-01-30 09:52 UTC, nboufSD commented on src/actions.ts
> +    }
レビューありがとうございます！

dispatch(AddAudienceInPreparation({ peerId, stream, dataURL }));
の前後に持ってきたのですが、前後関係なく、AddAudienceInPreparationが無限に呼び出されるようになってしまいます。
自分的には、if (stream && !dataURL)が必要そうに感じるのですが、どうでしょうか？

2021-02-01 03:49 UTC, dadaa requested changes

2021-02-01 03:49 UTC, dadaa commented on src/actions.ts
> +  const isExistaudience = state.audiences.find(a => a.peerId === peerId);
もしこの audience があるのなら、この audience に対して、dataURL ないし stream を更新したいです。
そして、この後の処理がなんら必要なくなるはずです。
あと、`is` から始まる変数は、基本的に bool を表すので、ここでは適していないと思います。

2021-02-01 04:24 UTC, nboufSD commented on src/actions.ts
> +  const isExistaudience = state.audiences.find(a => a.peerId === peerId);
レビューありがとうございます。

audienceの更新についての修正を忘れていました。すいません！

質問なのですが、この後の処理とは何の処理のことなのでしょうか？

2021-02-01 04:27 UTC, nboufSD commented on src/actions.ts
> +  const isExistaudience = state.audiences.find(a => a.peerId === peerId);
また、audienceの更新についてですが、新しいactionを作って更新するか、AddAudienceInPreparationの中でaudienceが存在するかの判定を行なって、存在していれば更新する方法の２通りを思いつきましたが、どちらが良いのでしょうか？

2021-02-01 04:28 UTC, dadaa commented on src/actions.ts
> +  const isExistaudience = state.audiences.find(a => a.peerId === peerId);
コードをよーくみればわかるのですが、`isExistaudience` があった場合、結局何もしてないことがわかると思います。なので、これに続く処理は不必要と思います。

2021-02-01 04:30 UTC, dadaa commented on src/actions.ts
> +  const isExistaudience = state.audiences.find(a => a.peerId === peerId);
AddAudienceInPreparation の中で更新するのは、このアクションの名前とずいぶん乖離が生じます。コードを見た際にも混乱するので、新しいアクション UpdateAudience() を作ってください。

2021-02-01 04:35 UTC, nboufSD commented on src/actions.ts
> +  const isExistaudience = state.audiences.find(a => a.peerId === peerId);
audienceの更新にはUpdateAudience()で行います！

今考えているのは、isExistaudienceが存在している場合に、UpdateAudience()を呼ぶようにしようと考えているのですが、
大丈夫でしょうか？

2021-02-01 04:37 UTC, dadaa commented on src/actions.ts
> +  const isExistaudience = state.audiences.find(a => a.peerId === peerId);
ほかの選択肢はあまり考えられないですね。

2021-02-01 05:25 UTC, dadaa commented on src/actions.ts
> +  const audienceExist = state.audiences.find(a => a.peerId === peerId);
えっと、`audienceExist` があれば、UpdateAudience するだけで、この後に続く  `if (audienceInPreparation) {` とか、`if (stream && dataURL) {` の処理はまったく必要ありません。
したがって、
```
const audienceExist = state.audiences.find(a => a.peerId === peerId);
if (audienceExist) {
 ... UpdateAudience
  return;
}
```
とかすれば無駄な処理をしないですみます。

また、`audienceExist` を評価する際には `audienceInPreparation` は必要ないので、`audienceExist` での評価が終わったあとに `const audienceInPreparation = state.audiencesInPreparation.find` するべきです。

2021-02-01 06:35 UTC, nboufSD commented on src/actions.ts
> +  const audienceExist = state.audiences.find(a => a.peerId === peerId);
ちょっとまだ理解ができていないのですが、上記のif (stream && dataURL) 〜がなければ

2021-02-01 06:58 UTC, dadaa commented on src/actions.ts
> +  const audienceExist = state.audiences.find(a => a.peerId === peerId);
もうすでに `if (stream && dataURL)` で 一度 AddAudience が終わったあとに呼ばれた `updateAudienceInPreparation` に対応する処理を書きたいのだと思います。
もういちど、３が入ってきたときの１の人の処理で ２ からの icon-updated が来たときの動きを調べてみればわかると思いますけど、すでに state.audiences ができあがっているので、かわりに UpdateAudience をしたい。ということなのだと思います。
いまいちど、動きを確かめてくれませんか?

2021-02-01 07:33 UTC, nboufSD commented on src/actions.ts
> +  const audienceExist = state.audiences.find(a => a.peerId === peerId);
すみません…今はどの動きを確かめればいいのかすらわからないので、
確認なのですが、どの処理が不要なのか具体的に教えていただいても宜しいでしょうか…？

2021-02-01 07:45 UTC, dadaa requested changes

2021-02-01 07:45 UTC, dadaa commented on src/actions.ts
> +  const audienceExist = state.audiences.find(a => a.peerId === peerId);
```
function updateAudienceInPreparation(
  dispatch: ThunkDispatch<TStore, void, AnyAction>,
  state: IState,
  peerId: string,
  stream?: any,
  dataURL?: string
) {
  const audienceExist = state.audiences.find(a => a.peerId === peerId);

  if (audienceExist) {
    dispatch(UpdateAudience({ peerId, stream, dataURL }));
    return;
  }

  const audienceInPreparation = state.audiencesInPreparation.find(
    a => a.peerId === peerId
  );

  if (audienceInPreparation) {
    stream = stream || audienceInPreparation.stream;
    dataURL = dataURL || audienceInPreparation.dataURL;
  }

  if (stream && dataURL) {
    dispatch(AddAudience({ peerId, stream, dataURL }));
  } else {
    dispatch(AddAudienceInPreparation({ peerId, stream, dataURL }));

    if (!state.room) {
      return;
    }

    const mine = state.audiences.find(
      a => a.peerId === state.localPeer?.id
    );
    if (mine) {
      state.room.send({
        type: "icon-updated",
        dataURL: mine.dataURL,
        peerId: mine.peerId,
      });
    }
    // Tell who is a presenter now, to peer joined newly.
    if (state.presenter) {
      state.room.send({
        type: "peer-selected",
        peerId: state.presenter.peerId,
      });
      state.room.send({
        type: "location-muted",
        isMapEnabled: state.isPresenterMapEnabled,
      });
      state.room.send({
        type: "location-changed",
        lat: state.map.lat,
        lng: state.map.lng,
      });
    }
  }
}
```

2021-02-01 07:45 UTC, dadaa commented on src/reducer.ts
>      }
```
    const index = state.audiences.findIndex(a => a.peerId === peerId);
    let audiences = state.audiences;
    let audience = audiences[index];

    if (stream) {
      audience = Object.assign({}, audience, { stream });
    } else {
      audience = Object.assign({}, audience, { dataURL });
    }

    audiences[index] = audience;
    return Object.assign({}, state, { audiences: [...audiences] });
```

2021-02-01 08:50 UTC, dadaa requested changes

2021-02-01 08:50 UTC, dadaa commented on src/actions.ts
> +  const state = store.getState()?.state;
これが必要なのは icon-updatd だけなので、そこに移動してください。

2021-02-01 08:50 UTC, dadaa commented on src/reducer.ts
> +  AddAudienceInPreparation,
アルファベット順にお願いします。

2021-02-01 09:59 UTC, nboufSD commented on src/actions.ts
> +  const state = store.getState()?.state;
修正しました！

2021-02-01 10:06 UTC, nboufSD commented on src/reducer.ts
> +  AddAudienceInPreparation,
すいません！修正しました！

2021-02-01 10:11 UTC, dadaa commented on src/actions.ts
> +}>("ADD_AUDIENCE");
ここもアルファベット順でしたね。

2021-02-01 10:13 UTC, dadaa approved these changes
アルファベット順に直していただくことを前提にオーケーです。

2021-02-01 11:29 UTC, merged