create demo
telepresence-platform/cocosoco pull request #91
Opened 2021-01-21 10:48 UTC by nboufSD

2021-01-21 14:58 UTC, dadaa reviewed
ありがとうございます！問題ないと思います！
一つだけ nit を残したので、確認してくださいー

2021-01-21 14:58 UTC, dadaa commented on src/components/AudienceList.css
> +  .audience-list {
nit: 余分なスペースが入ってるみたいです。

2021-01-21 15:15 UTC, dadaa approved these changes
先程の余分なスペースを削除したプルリクが改めて送られてくることを前提に、Approve しておきます。

2021-01-22 03:35 UTC, dadaa requested changes
ありがとうございますー
class 名の書き方をちょっと変えましょうー

2021-01-22 03:35 UTC, dadaa commented on src/components/AudienceItem.tsx
> +          (isMuted ? "audience-item--mine" : "")
nit: 以下の方が余分なスペースが入る可能性が少なくなるかな？
(class を追加するときに、スペース+class名 に変更)
```
"audience-item" +
  (isSelected ? " audience-item--selected" : "") +
  (isMuted ? " audience-item--mine" : "")
  ```

2021-01-22 03:35 UTC, dadaa commented on src/components/AudienceItem.tsx
> +            (isMuted ? "audience-item__icon--mine" : "")
同様に。

2021-01-22 04:34 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +          (isMuted ? "audience-item--mine" : "")
ありがとうございます！
その方法で修正します！

2021-01-22 04:34 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +            (isMuted ? "audience-item__icon--mine" : "")
修正しました！

2021-01-22 04:37 UTC, dadaa commented on src/components/AudienceItem.tsx
> +          (isSelected ? " audience-item--selected " : "") +
" audience-item--selected "
後ろの余分なスペースがついているので削除しましょう。

2021-01-22 05:33 UTC, nboufSD commented on src/components/AudienceItem.tsx
> +          (isSelected ? " audience-item--selected " : "") +
すみません！修正しました！

2021-01-22 05:41 UTC, dadaa approved these changes

2021-01-22 09:26 UTC, merged